/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 34tvEQuyqfK98iGCjMbawB
// Component: LqSOOVk2zON6
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { usePlasmicDataOp } from "@plasmicapp/react-web/lib/data-sources";
import SectionAdPlaceholder from "../../SectionAdPlaceholder"; // plasmic-import: MWRaB-Trol6D/component
import SectionBreadcrumbs from "../../SectionBreadcrumbs"; // plasmic-import: TPxxugejEIaa/component
import SectionInternalHeroTitleSectionV2 from "../../SectionInternalHeroTitleSectionV2"; // plasmic-import: xL1xlGlXhY87/component
import HtmlContentfulHtmlLoader from "../../HtmlContentfulHtmlLoader"; // plasmic-import: yo4cxXaLxoOm/component
import SectionAccordionSectionTemplate from "../../SectionAccordionSectionTemplate"; // plasmic-import: RAMfSAUHc9g1/component
import BlockAsshMissionBlueBlock from "../../BlockAsshMissionBlueBlock"; // plasmic-import: oMTPDeBb_fES/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/styleTokensProvider
import { _useStyleTokens as useStyleTokens_antd_5_hostless } from "../antd_5_hostless/PlasmicStyleTokensProvider"; // plasmic-import: ohDidvG9XsCeFumugENU3J/styleTokensProvider
import { _useStyleTokens as useStyleTokens_plasmic_rich_components } from "../plasmic_rich_components/PlasmicStyleTokensProvider"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/projectcss
import sty from "./PlasmicJournalCmeCreditExams.module.css"; // plasmic-import: LqSOOVk2zON6/css

createPlasmicElementProxy;

export const PlasmicJournalCmeCreditExams__VariantProps = new Array();

export const PlasmicJournalCmeCreditExams__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicJournalCmeCreditExams__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  let [$queries, setDollarQueries] = React.useState({});
  const new$Queries = {
    getHtmlContent: usePlasmicDataOp(() => {
      return {
        sourceId: "tbVV8SR67UpQ6Z9zuPcDPB",
        opId: "4030023b-1dcd-4f29-b7cd-2b4b3180e795",
        userArgs: {},
        cacheKey: `plasmic.$.4030023b-1dcd-4f29-b7cd-2b4b3180e795.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);
    $queries = new$Queries;
  }
  const styleTokensClassNames = _useStyleTokens();
  const styleTokensClassNames_antd_5_hostless =
    useStyleTokens_antd_5_hostless();
  const styleTokensClassNames_plasmic_rich_components =
    useStyleTokens_plasmic_rich_components();
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">
          {PlasmicJournalCmeCreditExams.pageMetadata.title}
        </title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicJournalCmeCreditExams.pageMetadata.title}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicJournalCmeCreditExams.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            styleTokensClassNames_antd_5_hostless,
            styleTokensClassNames_plasmic_rich_components,
            sty.root
          )}
        >
          <SectionAdPlaceholder
            className={classNames(
              "__wab_instance",
              sty.sectionAdPlaceholder___3YdPz
            )}
          />

          <SectionBreadcrumbs
            data-plasmic-name={"sectionBreadcrumbs"}
            data-plasmic-override={overrides.sectionBreadcrumbs}
            className={classNames("__wab_instance", sty.sectionBreadcrumbs)}
            currentPagePath={"/news-publications/journal-cme-credit-exams"}
          />

          <SectionInternalHeroTitleSectionV2
            data-plasmic-name={"sectionInternalHeroTitleSectionV2"}
            data-plasmic-override={overrides.sectionInternalHeroTitleSectionV2}
            className={classNames(
              "__wab_instance",
              sty.sectionInternalHeroTitleSectionV2
            )}
            title={"Hero: Journal CME Credit Exams - Title Card"}
          />

          <div className={classNames(projectcss.all, sty.freeBox___7XvKd)}>
            <HtmlContentfulHtmlLoader
              data-plasmic-name={"htmlContentfulHtmlLoader"}
              data-plasmic-override={overrides.htmlContentfulHtmlLoader}
              className={classNames(
                "__wab_instance",
                sty.htmlContentfulHtmlLoader
              )}
              title={"ASSH Journal CME Credit Exams"}
            />

            {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
              (() => {
                try {
                  return $queries.getHtmlContent.data.response.items;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return [];
                  }
                  throw e;
                }
              })()
            ).map((__plasmic_item_0, __plasmic_idx_0) => {
              const currentItem = __plasmic_item_0;
              const currentIndex = __plasmic_idx_0;
              return (
                <div
                  className={classNames(projectcss.all, sty.freeBox__iXcYo)}
                  key={currentIndex}
                >
                  <SectionAccordionSectionTemplate
                    data-plasmic-name={"sectionAccordionSectionTemplate"}
                    data-plasmic-override={
                      overrides.sectionAccordionSectionTemplate
                    }
                    bodyContent={(() => {
                      try {
                        return currentItem.fields.bodyContent;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                    className={classNames(
                      "__wab_instance",
                      sty.sectionAccordionSectionTemplate
                    )}
                    title={(() => {
                      try {
                        return currentItem.fields.title;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                  />
                </div>
              );
            })}
          </div>
          <SectionAdPlaceholder
            className={classNames(
              "__wab_instance",
              sty.sectionAdPlaceholder__wrFro
            )}
          />

          <BlockAsshMissionBlueBlock
            data-plasmic-name={"blockAsshMissionBlueBlock"}
            data-plasmic-override={overrides.blockAsshMissionBlueBlock}
            className={classNames(
              "__wab_instance",
              sty.blockAsshMissionBlueBlock
            )}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "sectionBreadcrumbs",
    "sectionInternalHeroTitleSectionV2",
    "htmlContentfulHtmlLoader",
    "sectionAccordionSectionTemplate",
    "blockAsshMissionBlueBlock"
  ],

  sectionBreadcrumbs: ["sectionBreadcrumbs"],
  sectionInternalHeroTitleSectionV2: ["sectionInternalHeroTitleSectionV2"],
  htmlContentfulHtmlLoader: ["htmlContentfulHtmlLoader"],
  sectionAccordionSectionTemplate: ["sectionAccordionSectionTemplate"],
  blockAsshMissionBlueBlock: ["blockAsshMissionBlueBlock"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicJournalCmeCreditExams__ArgProps,
          internalVariantPropNames: PlasmicJournalCmeCreditExams__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicJournalCmeCreditExams__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicJournalCmeCreditExams";
  } else {
    func.displayName = `PlasmicJournalCmeCreditExams.${nodeName}`;
  }
  return func;
}

export const PlasmicJournalCmeCreditExams = Object.assign(
  // Top-level PlasmicJournalCmeCreditExams renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    sectionBreadcrumbs: makeNodeComponent("sectionBreadcrumbs"),
    sectionInternalHeroTitleSectionV2: makeNodeComponent(
      "sectionInternalHeroTitleSectionV2"
    ),
    htmlContentfulHtmlLoader: makeNodeComponent("htmlContentfulHtmlLoader"),
    sectionAccordionSectionTemplate: makeNodeComponent(
      "sectionAccordionSectionTemplate"
    ),
    blockAsshMissionBlueBlock: makeNodeComponent("blockAsshMissionBlueBlock"),
    // Metadata about props expected for PlasmicJournalCmeCreditExams
    internalVariantProps: PlasmicJournalCmeCreditExams__VariantProps,
    internalArgProps: PlasmicJournalCmeCreditExams__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Journal CME Credit Exams | News & Publications | ASSH",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicJournalCmeCreditExams;
/* prettier-ignore-end */
