/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 34tvEQuyqfK98iGCjMbawB
// Component: jTSozzeU-2tC
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { usePlasmicDataOp } from "@plasmicapp/react-web/lib/data-sources";
import ComponentFeaturedWebsiteCard from "../../ComponentFeaturedWebsiteCard"; // plasmic-import: mcITMmfoX9ZQ/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/styleTokensProvider
import { _useStyleTokens as useStyleTokens_antd_5_hostless } from "../antd_5_hostless/PlasmicStyleTokensProvider"; // plasmic-import: ohDidvG9XsCeFumugENU3J/styleTokensProvider
import { _useStyleTokens as useStyleTokens_plasmic_rich_components } from "../plasmic_rich_components/PlasmicStyleTokensProvider"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/projectcss
import sty from "./PlasmicJaTestHome.module.css"; // plasmic-import: jTSozzeU-2tC/css

createPlasmicElementProxy;

export const PlasmicJaTestHome__VariantProps = new Array();

export const PlasmicJaTestHome__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicJaTestHome__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  let [$queries, setDollarQueries] = React.useState({});
  const new$Queries = {
    updatesQuery: usePlasmicDataOp(() => {
      return {
        sourceId: "tbVV8SR67UpQ6Z9zuPcDPB",
        opId: "cd78a920-c2ba-4464-81cc-cbd12c3ae506",
        userArgs: {},
        cacheKey: `plasmic.$.cd78a920-c2ba-4464-81cc-cbd12c3ae506.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);
    $queries = new$Queries;
  }
  const styleTokensClassNames = _useStyleTokens();
  const styleTokensClassNames_antd_5_hostless =
    useStyleTokens_antd_5_hostless();
  const styleTokensClassNames_plasmic_rich_components =
    useStyleTokens_plasmic_rich_components();
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicJaTestHome.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicJaTestHome.pageMetadata.title}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicJaTestHome.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"asshHome"}
          data-plasmic-override={overrides.asshHome}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            styleTokensClassNames_antd_5_hostless,
            styleTokensClassNames_plasmic_rich_components,
            sty.asshHome
          )}
        >
          <ComponentFeaturedWebsiteCard
            data-plasmic-name={"componentFeaturedWebsiteCard"}
            data-plasmic-override={overrides.componentFeaturedWebsiteCard}
            className={classNames(
              "__wab_instance",
              sty.componentFeaturedWebsiteCard
            )}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  asshHome: ["asshHome", "componentFeaturedWebsiteCard"],
  componentFeaturedWebsiteCard: ["componentFeaturedWebsiteCard"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicJaTestHome__ArgProps,
          internalVariantPropNames: PlasmicJaTestHome__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicJaTestHome__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "asshHome") {
    func.displayName = "PlasmicJaTestHome";
  } else {
    func.displayName = `PlasmicJaTestHome.${nodeName}`;
  }
  return func;
}

export const PlasmicJaTestHome = Object.assign(
  // Top-level PlasmicJaTestHome renders the root element
  makeNodeComponent("asshHome"),
  {
    // Helper components rendering sub-elements
    componentFeaturedWebsiteCard: makeNodeComponent(
      "componentFeaturedWebsiteCard"
    ),
    // Metadata about props expected for PlasmicJaTestHome
    internalVariantProps: PlasmicJaTestHome__VariantProps,
    internalArgProps: PlasmicJaTestHome__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "ASSH Home",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicJaTestHome;
/* prettier-ignore-end */
