/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 34tvEQuyqfK98iGCjMbawB
// Component: kWFNkIbMjGR3
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import SectionAdPlaceholder from "../../SectionAdPlaceholder"; // plasmic-import: MWRaB-Trol6D/component
import SectionInternalHeroTitleSectionV2 from "../../SectionInternalHeroTitleSectionV2"; // plasmic-import: xL1xlGlXhY87/component
import BlockArticleCardList from "../../BlockArticleCardList"; // plasmic-import: HfgRxg6hxFsA/component
import SectionQuestion from "../../SectionQuestion"; // plasmic-import: 9B7ukqwaDf9R/component
import BlockAsshMissionBlueBlock from "../../BlockAsshMissionBlueBlock"; // plasmic-import: oMTPDeBb_fES/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/styleTokensProvider
import { _useStyleTokens as useStyleTokens_antd_5_hostless } from "../antd_5_hostless/PlasmicStyleTokensProvider"; // plasmic-import: ohDidvG9XsCeFumugENU3J/styleTokensProvider
import { _useStyleTokens as useStyleTokens_plasmic_rich_components } from "../plasmic_rich_components/PlasmicStyleTokensProvider"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/projectcss
import sty from "./PlasmicJobBoard.module.css"; // plasmic-import: kWFNkIbMjGR3/css

createPlasmicElementProxy;

export const PlasmicJobBoard__VariantProps = new Array();

export const PlasmicJobBoard__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicJobBoard__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const styleTokensClassNames = _useStyleTokens();
  const styleTokensClassNames_antd_5_hostless =
    useStyleTokens_antd_5_hostless();
  const styleTokensClassNames_plasmic_rich_components =
    useStyleTokens_plasmic_rich_components();
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicJobBoard.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicJobBoard.pageMetadata.title}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicJobBoard.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            styleTokensClassNames_antd_5_hostless,
            styleTokensClassNames_plasmic_rich_components,
            sty.root
          )}
        >
          <SectionAdPlaceholder
            className={classNames(
              "__wab_instance",
              sty.sectionAdPlaceholder__y5Ss7
            )}
          />

          <SectionInternalHeroTitleSectionV2
            data-plasmic-name={"sectionInternalHeroTitleSectionV2"}
            data-plasmic-override={overrides.sectionInternalHeroTitleSectionV2}
            className={classNames(
              "__wab_instance",
              sty.sectionInternalHeroTitleSectionV2
            )}
            title={"Hero: Job Board - Title Card"}
          />

          <div className={classNames(projectcss.all, sty.freeBox___6LNwq)}>
            <BlockArticleCardList
              className={classNames(
                "__wab_instance",
                sty.blockArticleCardList__cnncR
              )}
              name={"Job Board: Job Seekers Links"}
            />
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___9McX)}>
            <BlockArticleCardList
              className={classNames(
                "__wab_instance",
                sty.blockArticleCardList__eaJxv
              )}
              name={"Job Board: Employees Recruiters Links"}
            />
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__h4YJ9)}>
            <h3
              data-plasmic-name={"h3"}
              data-plasmic-override={overrides.h3}
              className={classNames(
                projectcss.all,
                projectcss.h3,
                projectcss.__wab_text,
                sty.h3
              )}
            >
              {"Need help?"}
            </h3>
            <SectionQuestion
              data-plasmic-name={"sectionQuestion"}
              data-plasmic-override={overrides.sectionQuestion}
              className={classNames("__wab_instance", sty.sectionQuestion)}
              name={"Job Board: Need Help?"}
            />
          </div>
          <SectionAdPlaceholder
            className={classNames(
              "__wab_instance",
              sty.sectionAdPlaceholder__uvRcQ
            )}
          />

          <BlockAsshMissionBlueBlock
            data-plasmic-name={"blockAsshMissionBlueBlock"}
            data-plasmic-override={overrides.blockAsshMissionBlueBlock}
            className={classNames(
              "__wab_instance",
              sty.blockAsshMissionBlueBlock
            )}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "sectionInternalHeroTitleSectionV2",
    "h3",
    "sectionQuestion",
    "blockAsshMissionBlueBlock"
  ],

  sectionInternalHeroTitleSectionV2: ["sectionInternalHeroTitleSectionV2"],
  h3: ["h3"],
  sectionQuestion: ["sectionQuestion"],
  blockAsshMissionBlueBlock: ["blockAsshMissionBlueBlock"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicJobBoard__ArgProps,
          internalVariantPropNames: PlasmicJobBoard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicJobBoard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicJobBoard";
  } else {
    func.displayName = `PlasmicJobBoard.${nodeName}`;
  }
  return func;
}

export const PlasmicJobBoard = Object.assign(
  // Top-level PlasmicJobBoard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    sectionInternalHeroTitleSectionV2: makeNodeComponent(
      "sectionInternalHeroTitleSectionV2"
    ),
    h3: makeNodeComponent("h3"),
    sectionQuestion: makeNodeComponent("sectionQuestion"),
    blockAsshMissionBlueBlock: makeNodeComponent("blockAsshMissionBlueBlock"),
    // Metadata about props expected for PlasmicJobBoard
    internalVariantProps: PlasmicJobBoard__VariantProps,
    internalArgProps: PlasmicJobBoard__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Job Board",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicJobBoard;
/* prettier-ignore-end */
