/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 34tvEQuyqfK98iGCjMbawB
// Component: 4sVxlULRtaDO
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import SectionAdPlaceholder from "../../SectionAdPlaceholder"; // plasmic-import: MWRaB-Trol6D/component
import SectionInternalHeroTitleSectionV2 from "../../SectionInternalHeroTitleSectionV2"; // plasmic-import: xL1xlGlXhY87/component
import ItemSectionTitleDescriptionItem from "../../ItemSectionTitleDescriptionItem"; // plasmic-import: jaOmCC9X_Oxf/component
import HtmlContentfulHtmlLoader from "../../HtmlContentfulHtmlLoader"; // plasmic-import: yo4cxXaLxoOm/component
import BlockArticleCardList from "../../BlockArticleCardList"; // plasmic-import: HfgRxg6hxFsA/component
import SectionMidPageBannerWithQuicklinks from "../../SectionMidPageBannerWithQuicklinks"; // plasmic-import: hQw6wQfUz2Ua/component
import SectionQuicklinksTable from "../../SectionQuicklinksTable"; // plasmic-import: dzBXgCr_C9up/component
import BlockAsshMissionBlueBlock from "../../BlockAsshMissionBlueBlock"; // plasmic-import: oMTPDeBb_fES/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/styleTokensProvider
import { _useStyleTokens as useStyleTokens_antd_5_hostless } from "../antd_5_hostless/PlasmicStyleTokensProvider"; // plasmic-import: ohDidvG9XsCeFumugENU3J/styleTokensProvider
import { _useStyleTokens as useStyleTokens_plasmic_rich_components } from "../plasmic_rich_components/PlasmicStyleTokensProvider"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/projectcss
import sty from "./PlasmicForResidentsAndFellows.module.css"; // plasmic-import: 4sVxlULRtaDO/css

createPlasmicElementProxy;

export const PlasmicForResidentsAndFellows__VariantProps = new Array();

export const PlasmicForResidentsAndFellows__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicForResidentsAndFellows__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const styleTokensClassNames = _useStyleTokens();
  const styleTokensClassNames_antd_5_hostless =
    useStyleTokens_antd_5_hostless();
  const styleTokensClassNames_plasmic_rich_components =
    useStyleTokens_plasmic_rich_components();
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">
          {PlasmicForResidentsAndFellows.pageMetadata.title}
        </title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicForResidentsAndFellows.pageMetadata.title}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicForResidentsAndFellows.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            styleTokensClassNames_antd_5_hostless,
            styleTokensClassNames_plasmic_rich_components,
            sty.root
          )}
        >
          <SectionAdPlaceholder
            className={classNames(
              "__wab_instance",
              sty.sectionAdPlaceholder__hYiQ
            )}
          />

          <SectionInternalHeroTitleSectionV2
            data-plasmic-name={"sectionInternalHeroTitleSectionV2"}
            data-plasmic-override={overrides.sectionInternalHeroTitleSectionV2}
            className={classNames(
              "__wab_instance",
              sty.sectionInternalHeroTitleSectionV2
            )}
            title={"Hero: For R&F - Title Card"}
          />

          <div className={classNames(projectcss.all, sty.freeBox__tb3ER)}>
            <ItemSectionTitleDescriptionItem
              data-plasmic-name={"itemSectionTitleDescriptionItem"}
              data-plasmic-override={overrides.itemSectionTitleDescriptionItem}
              className={classNames(
                "__wab_instance",
                sty.itemSectionTitleDescriptionItem
              )}
              descriptionSection={``}
              title={"How ASSH Supports Trainees"}
            />

            <HtmlContentfulHtmlLoader
              data-plasmic-name={"htmlContentfulHtmlLoader"}
              data-plasmic-override={overrides.htmlContentfulHtmlLoader}
              className={classNames(
                "__wab_instance",
                sty.htmlContentfulHtmlLoader
              )}
              title={"How ASSH Supports Trainees"}
            />

            <BlockArticleCardList
              data-plasmic-name={"blockArticleCardList"}
              data-plasmic-override={overrides.blockArticleCardList}
              className={classNames("__wab_instance", sty.blockArticleCardList)}
              name={"For R&F: Resident & Fellow Resources"}
            />
          </div>
          <SectionMidPageBannerWithQuicklinks
            data-plasmic-name={"sectionMidPageBannerWithQuicklinks"}
            data-plasmic-override={overrides.sectionMidPageBannerWithQuicklinks}
            className={classNames(
              "__wab_instance",
              sty.sectionMidPageBannerWithQuicklinks
            )}
          />

          <div className={classNames(projectcss.all, sty.freeBox__tmhb)}>
            <SectionQuicklinksTable
              data-plasmic-name={"sectionQuicklinksTable"}
              data-plasmic-override={overrides.sectionQuicklinksTable}
              className={classNames(
                "__wab_instance",
                sty.sectionQuicklinksTable
              )}
              columns={"_3Column"}
              name={"For R&F Quicklinks"}
            />
          </div>
          <SectionAdPlaceholder
            className={classNames(
              "__wab_instance",
              sty.sectionAdPlaceholder__gLss9
            )}
          />

          <BlockAsshMissionBlueBlock
            data-plasmic-name={"blockAsshMissionBlueBlock"}
            data-plasmic-override={overrides.blockAsshMissionBlueBlock}
            className={classNames(
              "__wab_instance",
              sty.blockAsshMissionBlueBlock
            )}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "sectionInternalHeroTitleSectionV2",
    "itemSectionTitleDescriptionItem",
    "htmlContentfulHtmlLoader",
    "blockArticleCardList",
    "sectionMidPageBannerWithQuicklinks",
    "sectionQuicklinksTable",
    "blockAsshMissionBlueBlock"
  ],

  sectionInternalHeroTitleSectionV2: ["sectionInternalHeroTitleSectionV2"],
  itemSectionTitleDescriptionItem: ["itemSectionTitleDescriptionItem"],
  htmlContentfulHtmlLoader: ["htmlContentfulHtmlLoader"],
  blockArticleCardList: ["blockArticleCardList"],
  sectionMidPageBannerWithQuicklinks: ["sectionMidPageBannerWithQuicklinks"],
  sectionQuicklinksTable: ["sectionQuicklinksTable"],
  blockAsshMissionBlueBlock: ["blockAsshMissionBlueBlock"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicForResidentsAndFellows__ArgProps,
          internalVariantPropNames: PlasmicForResidentsAndFellows__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicForResidentsAndFellows__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicForResidentsAndFellows";
  } else {
    func.displayName = `PlasmicForResidentsAndFellows.${nodeName}`;
  }
  return func;
}

export const PlasmicForResidentsAndFellows = Object.assign(
  // Top-level PlasmicForResidentsAndFellows renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    sectionInternalHeroTitleSectionV2: makeNodeComponent(
      "sectionInternalHeroTitleSectionV2"
    ),
    itemSectionTitleDescriptionItem: makeNodeComponent(
      "itemSectionTitleDescriptionItem"
    ),
    htmlContentfulHtmlLoader: makeNodeComponent("htmlContentfulHtmlLoader"),
    blockArticleCardList: makeNodeComponent("blockArticleCardList"),
    sectionMidPageBannerWithQuicklinks: makeNodeComponent(
      "sectionMidPageBannerWithQuicklinks"
    ),
    sectionQuicklinksTable: makeNodeComponent("sectionQuicklinksTable"),
    blockAsshMissionBlueBlock: makeNodeComponent("blockAsshMissionBlueBlock"),
    // Metadata about props expected for PlasmicForResidentsAndFellows
    internalVariantProps: PlasmicForResidentsAndFellows__VariantProps,
    internalArgProps: PlasmicForResidentsAndFellows__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "For Residents & Fellows",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicForResidentsAndFellows;
/* prettier-ignore-end */
