/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 34tvEQuyqfK98iGCjMbawB
// Component: oUDT_QRNoMZw
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { usePlasmicDataOp } from "@plasmicapp/react-web/lib/data-sources";
import SectionAdPlaceholder from "../../SectionAdPlaceholder"; // plasmic-import: MWRaB-Trol6D/component
import HtmlContentfulHtmlLoader from "../../HtmlContentfulHtmlLoader"; // plasmic-import: yo4cxXaLxoOm/component
import BlockTanCtaBlock from "../../BlockTanCtaBlock"; // plasmic-import: YJsN7RAC0P0B/component
import SectionAccordionSectionTemplate from "../../SectionAccordionSectionTemplate"; // plasmic-import: RAMfSAUHc9g1/component
import BlockQuoteBlock from "../../BlockQuoteBlock"; // plasmic-import: pkNfPBeJPFGR/component
import BlockMemberDashboard from "../../BlockMemberDashboard"; // plasmic-import: O2TSODJiol19/component
import BlockAsshMissionBlueBlock from "../../BlockAsshMissionBlueBlock"; // plasmic-import: oMTPDeBb_fES/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/styleTokensProvider
import { _useStyleTokens as useStyleTokens_antd_5_hostless } from "../antd_5_hostless/PlasmicStyleTokensProvider"; // plasmic-import: ohDidvG9XsCeFumugENU3J/styleTokensProvider
import { _useStyleTokens as useStyleTokens_plasmic_rich_components } from "../plasmic_rich_components/PlasmicStyleTokensProvider"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/projectcss
import sty from "./PlasmicCandidateMembership.module.css"; // plasmic-import: oUDT_QRNoMZw/css

createPlasmicElementProxy;

export const PlasmicCandidateMembership__VariantProps = new Array();

export const PlasmicCandidateMembership__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCandidateMembership__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  let [$queries, setDollarQueries] = React.useState({});
  const new$Queries = {
    getContent: usePlasmicDataOp(() => {
      return {
        sourceId: "tbVV8SR67UpQ6Z9zuPcDPB",
        opId: "d3dc9b6c-1b3c-4d7c-be29-8b5b635d3e8a",
        userArgs: {},
        cacheKey: `plasmic.$.d3dc9b6c-1b3c-4d7c-be29-8b5b635d3e8a.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);
    $queries = new$Queries;
  }
  const styleTokensClassNames = _useStyleTokens();
  const styleTokensClassNames_antd_5_hostless =
    useStyleTokens_antd_5_hostless();
  const styleTokensClassNames_plasmic_rich_components =
    useStyleTokens_plasmic_rich_components();
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            styleTokensClassNames_antd_5_hostless,
            styleTokensClassNames_plasmic_rich_components,
            sty.root
          )}
        >
          <SectionAdPlaceholder
            className={classNames(
              "__wab_instance",
              sty.sectionAdPlaceholder___0QukV
            )}
          />

          <div
            data-plasmic-name={"columns"}
            data-plasmic-override={overrides.columns}
            className={classNames(projectcss.all, sty.columns)}
          >
            <div className={classNames(projectcss.all, sty.column__wwaRq)}>
              <HtmlContentfulHtmlLoader
                data-plasmic-name={"htmlContentfulHtmlLoader"}
                data-plasmic-override={overrides.htmlContentfulHtmlLoader}
                className={classNames(
                  "__wab_instance",
                  sty.htmlContentfulHtmlLoader
                )}
                title={"Candidate Membership"}
              />

              <BlockTanCtaBlock
                data-plasmic-name={"blockTanCtaBlock"}
                data-plasmic-override={overrides.blockTanCtaBlock}
                className={classNames("__wab_instance", sty.blockTanCtaBlock)}
                linkText={``}
                linkUrl={``}
                text2={``}
                title={"Tan CTA Block - Candidate Membership"}
              />

              {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
                (() => {
                  try {
                    return $queries.getContent.data.response.items;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return [];
                    }
                    throw e;
                  }
                })()
              ).map((__plasmic_item_0, __plasmic_idx_0) => {
                const currentItem = __plasmic_item_0;
                const currentIndex = __plasmic_idx_0;
                return (
                  <div
                    data-plasmic-name={"freeBox"}
                    data-plasmic-override={overrides.freeBox}
                    className={classNames(projectcss.all, sty.freeBox)}
                    key={currentIndex}
                  >
                    <SectionAccordionSectionTemplate
                      data-plasmic-name={"sectionAccordionSectionTemplate"}
                      data-plasmic-override={
                        overrides.sectionAccordionSectionTemplate
                      }
                      bodyContent={(() => {
                        try {
                          return currentItem.fields.bodyContent;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()}
                      className={classNames(
                        "__wab_instance",
                        sty.sectionAccordionSectionTemplate
                      )}
                      title={(() => {
                        try {
                          return currentItem.fields.title;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()}
                    />
                  </div>
                );
              })}
            </div>
            <div className={classNames(projectcss.all, sty.column__qFvhz)}>
              <BlockQuoteBlock
                data-plasmic-name={"blockQuoteBlock"}
                data-plasmic-override={overrides.blockQuoteBlock}
                className={classNames("__wab_instance", sty.blockQuoteBlock)}
              />

              <BlockMemberDashboard
                data-plasmic-name={"blockMemberDashboard"}
                data-plasmic-override={overrides.blockMemberDashboard}
                className={classNames(
                  "__wab_instance",
                  sty.blockMemberDashboard
                )}
              />
            </div>
          </div>
          <SectionAdPlaceholder
            className={classNames(
              "__wab_instance",
              sty.sectionAdPlaceholder__rDhxN
            )}
          />

          <BlockAsshMissionBlueBlock
            data-plasmic-name={"blockAsshMissionBlueBlock"}
            data-plasmic-override={overrides.blockAsshMissionBlueBlock}
            className={classNames(
              "__wab_instance",
              sty.blockAsshMissionBlueBlock
            )}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "columns",
    "htmlContentfulHtmlLoader",
    "blockTanCtaBlock",
    "freeBox",
    "sectionAccordionSectionTemplate",
    "blockQuoteBlock",
    "blockMemberDashboard",
    "blockAsshMissionBlueBlock"
  ],

  columns: [
    "columns",
    "htmlContentfulHtmlLoader",
    "blockTanCtaBlock",
    "freeBox",
    "sectionAccordionSectionTemplate",
    "blockQuoteBlock",
    "blockMemberDashboard"
  ],

  htmlContentfulHtmlLoader: ["htmlContentfulHtmlLoader"],
  blockTanCtaBlock: ["blockTanCtaBlock"],
  freeBox: ["freeBox", "sectionAccordionSectionTemplate"],
  sectionAccordionSectionTemplate: ["sectionAccordionSectionTemplate"],
  blockQuoteBlock: ["blockQuoteBlock"],
  blockMemberDashboard: ["blockMemberDashboard"],
  blockAsshMissionBlueBlock: ["blockAsshMissionBlueBlock"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCandidateMembership__ArgProps,
          internalVariantPropNames: PlasmicCandidateMembership__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCandidateMembership__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCandidateMembership";
  } else {
    func.displayName = `PlasmicCandidateMembership.${nodeName}`;
  }
  return func;
}

export const PlasmicCandidateMembership = Object.assign(
  // Top-level PlasmicCandidateMembership renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    columns: makeNodeComponent("columns"),
    htmlContentfulHtmlLoader: makeNodeComponent("htmlContentfulHtmlLoader"),
    blockTanCtaBlock: makeNodeComponent("blockTanCtaBlock"),
    freeBox: makeNodeComponent("freeBox"),
    sectionAccordionSectionTemplate: makeNodeComponent(
      "sectionAccordionSectionTemplate"
    ),
    blockQuoteBlock: makeNodeComponent("blockQuoteBlock"),
    blockMemberDashboard: makeNodeComponent("blockMemberDashboard"),
    blockAsshMissionBlueBlock: makeNodeComponent("blockAsshMissionBlueBlock"),
    // Metadata about props expected for PlasmicCandidateMembership
    internalVariantProps: PlasmicCandidateMembership__VariantProps,
    internalArgProps: PlasmicCandidateMembership__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicCandidateMembership;
/* prettier-ignore-end */
