/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 34tvEQuyqfK98iGCjMbawB
// Component: cRyvkSsQTGRv
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { usePlasmicDataOp } from "@plasmicapp/react-web/lib/data-sources";
import ItemAd from "../../ItemAd"; // plasmic-import: GN0Rszdi6Y-X/component
import SectionInternalHeroTitleSectionV2 from "../../SectionInternalHeroTitleSectionV2"; // plasmic-import: xL1xlGlXhY87/component
import HtmlContentfulHtmlLoader from "../../HtmlContentfulHtmlLoader"; // plasmic-import: yo4cxXaLxoOm/component
import SectionAccordionSectionTemplate from "../../SectionAccordionSectionTemplate"; // plasmic-import: RAMfSAUHc9g1/component
import BlockAsshMissionBlueBlock from "../../BlockAsshMissionBlueBlock"; // plasmic-import: oMTPDeBb_fES/component
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/projectcss
import sty from "./PlasmicPartnerMailingLists.module.css"; // plasmic-import: cRyvkSsQTGRv/css

createPlasmicElementProxy;

export const PlasmicPartnerMailingLists__VariantProps = new Array();

export const PlasmicPartnerMailingLists__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPartnerMailingLists__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  let [$queries, setDollarQueries] = React.useState({});
  const new$Queries = {
    getHtmlContent: usePlasmicDataOp(() => {
      return {
        sourceId: "tbVV8SR67UpQ6Z9zuPcDPB",
        opId: "404059a3-d091-4d39-a91d-83752991d899",
        userArgs: {},
        cacheKey: `plasmic.$.404059a3-d091-4d39-a91d-83752991d899.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);
    $queries = new$Queries;
  }
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">
          {PlasmicPartnerMailingLists.pageMetadata.title}
        </title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicPartnerMailingLists.pageMetadata.title}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicPartnerMailingLists.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <ItemAd className={classNames("__wab_instance", sty.itemAd__oJrAp)} />
          <SectionInternalHeroTitleSectionV2
            data-plasmic-name={"sectionInternalHeroTitleSectionV2"}
            data-plasmic-override={overrides.sectionInternalHeroTitleSectionV2}
            className={classNames(
              "__wab_instance",
              sty.sectionInternalHeroTitleSectionV2
            )}
            title={"Hero: Partner Mailing Lists - Title Card"}
          />

          <div className={classNames(projectcss.all, sty.freeBox__nQBal)}>
            <HtmlContentfulHtmlLoader
              data-plasmic-name={"htmlContentfulHtmlLoader"}
              data-plasmic-override={overrides.htmlContentfulHtmlLoader}
              className={classNames(
                "__wab_instance",
                sty.htmlContentfulHtmlLoader
              )}
              title={"Mailing Lists"}
            />

            {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
              (() => {
                try {
                  return $queries.getHtmlContent.data.response.items;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return [];
                  }
                  throw e;
                }
              })()
            ).map((__plasmic_item_0, __plasmic_idx_0) => {
              const currentItem = __plasmic_item_0;
              const currentIndex = __plasmic_idx_0;
              return (
                <div
                  className={classNames(projectcss.all, sty.freeBox__c8LeC)}
                  key={currentIndex}
                >
                  <SectionAccordionSectionTemplate
                    data-plasmic-name={"sectionAccordionSectionTemplate"}
                    data-plasmic-override={
                      overrides.sectionAccordionSectionTemplate
                    }
                    bodyContent={(() => {
                      try {
                        return currentItem.fields.bodyContent;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return ``;
                        }
                        throw e;
                      }
                    })()}
                    className={classNames(
                      "__wab_instance",
                      sty.sectionAccordionSectionTemplate
                    )}
                    title={(() => {
                      try {
                        return currentItem.fields.title;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return ``;
                        }
                        throw e;
                      }
                    })()}
                  />
                </div>
              );
            })}
          </div>
          <ItemAd className={classNames("__wab_instance", sty.itemAd__pxpD)} />
          <BlockAsshMissionBlueBlock
            data-plasmic-name={"blockAsshMissionBlueBlock"}
            data-plasmic-override={overrides.blockAsshMissionBlueBlock}
            className={classNames(
              "__wab_instance",
              sty.blockAsshMissionBlueBlock
            )}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "sectionInternalHeroTitleSectionV2",
    "htmlContentfulHtmlLoader",
    "sectionAccordionSectionTemplate",
    "blockAsshMissionBlueBlock"
  ],

  sectionInternalHeroTitleSectionV2: ["sectionInternalHeroTitleSectionV2"],
  htmlContentfulHtmlLoader: ["htmlContentfulHtmlLoader"],
  sectionAccordionSectionTemplate: ["sectionAccordionSectionTemplate"],
  blockAsshMissionBlueBlock: ["blockAsshMissionBlueBlock"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPartnerMailingLists__ArgProps,
          internalVariantPropNames: PlasmicPartnerMailingLists__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPartnerMailingLists__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPartnerMailingLists";
  } else {
    func.displayName = `PlasmicPartnerMailingLists.${nodeName}`;
  }
  return func;
}

export const PlasmicPartnerMailingLists = Object.assign(
  // Top-level PlasmicPartnerMailingLists renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    sectionInternalHeroTitleSectionV2: makeNodeComponent(
      "sectionInternalHeroTitleSectionV2"
    ),
    htmlContentfulHtmlLoader: makeNodeComponent("htmlContentfulHtmlLoader"),
    sectionAccordionSectionTemplate: makeNodeComponent(
      "sectionAccordionSectionTemplate"
    ),
    blockAsshMissionBlueBlock: makeNodeComponent("blockAsshMissionBlueBlock"),
    // Metadata about props expected for PlasmicPartnerMailingLists
    internalVariantProps: PlasmicPartnerMailingLists__VariantProps,
    internalArgProps: PlasmicPartnerMailingLists__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Mailing Lists | About | ASSH",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicPartnerMailingLists;
/* prettier-ignore-end */
