/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 34tvEQuyqfK98iGCjMbawB
// Component: hQw6wQfUz2Ua
import * as React from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  hasVariant,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { usePlasmicDataOp } from "@plasmicapp/react-web/lib/data-sources";
import ButtonPrimary from "../../ButtonPrimary"; // plasmic-import: -2HqLDJqJBwh/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/styleTokensProvider
import { _useStyleTokens as useStyleTokens_antd_5_hostless } from "../antd_5_hostless/PlasmicStyleTokensProvider"; // plasmic-import: ohDidvG9XsCeFumugENU3J/styleTokensProvider
import { _useStyleTokens as useStyleTokens_plasmic_rich_components } from "../plasmic_rich_components/PlasmicStyleTokensProvider"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/projectcss
import sty from "./PlasmicSectionMidPageBannerWithQuicklinks.module.css"; // plasmic-import: hQw6wQfUz2Ua/css
import ChevronRight2Icon from "./icons/PlasmicIcon__ChevronRight2"; // plasmic-import: TySuoJlWGjIs/icon

createPlasmicElementProxy;

export const PlasmicSectionMidPageBannerWithQuicklinks__VariantProps =
  new Array();

export const PlasmicSectionMidPageBannerWithQuicklinks__ArgProps = new Array(
  "heroName"
);

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSectionMidPageBannerWithQuicklinks__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          heroName: "For R&F - Mid-page CTA"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  let [$queries, setDollarQueries] = React.useState({});
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "quicklinks",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return (() => {
                const entryMap = Object.fromEntries(
                  $queries.getHero.data.response.includes.Entry.map(entry => [
                    entry.sys.id,
                    entry
                  ])
                );
                return $queries.getHero.data.response.items[0].fields.options
                  .map(link => {
                    const entry = entryMap[link.sys.id];
                    return {
                      id: link.sys.id,
                      label: entry?.fields.label || "Label missing",
                      order: Number(entry?.fields.order) || 0,
                      column: entry?.fields.column ?? 0,
                      url: entry?.fields.url || "#",
                      showExternalIcon: entry?.fields.showExternalIcon || false,
                      subText: entry?.fields.subText || ""
                    };
                  })
                  .sort((a, b) => a.order - b.order);
              })();
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $refs
  });
  const new$Queries = {
    getHero: usePlasmicDataOp(() => {
      return {
        sourceId: "tbVV8SR67UpQ6Z9zuPcDPB",
        opId: "84ab1dbe-22a0-4ab0-b1ff-3bd83c164121",
        userArgs: {
          params: [$props.heroName]
        },
        cacheKey: `plasmic.$.84ab1dbe-22a0-4ab0-b1ff-3bd83c164121.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);
    $queries = new$Queries;
  }
  const globalVariants = _useGlobalVariants();
  const styleTokensClassNames = _useStyleTokens();
  const styleTokensClassNames_antd_5_hostless =
    useStyleTokens_antd_5_hostless();
  const styleTokensClassNames_plasmic_rich_components =
    useStyleTokens_plasmic_rich_components();
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        styleTokensClassNames_antd_5_hostless,
        styleTokensClassNames_plasmic_rich_components,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__xFLp)}>
        <div
          data-plasmic-name={"columns"}
          data-plasmic-override={overrides.columns}
          className={classNames(projectcss.all, sty.columns)}
        >
          <div className={classNames(projectcss.all, sty.column__i3PJd)}>
            <div
              data-plasmic-name={"frame12"}
              data-plasmic-override={overrides.frame12}
              className={classNames(projectcss.all, sty.frame12)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___44J48
                )}
              >
                <React.Fragment>
                  {(() => {
                    try {
                      return $queries.getHero.data.response.items[0].fields
                        .section;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "MEMBERSHIP";
                      }
                      throw e;
                    }
                  })()}
                </React.Fragment>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___5XtOu
                )}
              >
                <React.Fragment>
                  {(() => {
                    try {
                      return $queries.getHero.data.response.items[0].fields
                        .header;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "New for Members: Shoulder CPT Codes in ASSH Coding App";
                      }
                      throw e;
                    }
                  })()}
                </React.Fragment>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qgr6L
                )}
              >
                <React.Fragment>
                  {(() => {
                    try {
                      return $queries.getHero.data.response.items[0].fields
                        .description;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "Shoulder-based CPT codes have now been added to the ASSH\u2019s Coding App! Free for members, the Coding App contains thousands of CPT codes with other built-in tools to help you code easier and more efficiently.";
                      }
                      throw e;
                    }
                  })()}
                </React.Fragment>
              </div>
              <ButtonPrimary
                data-plasmic-name={"buttonPrimary"}
                data-plasmic-override={overrides.buttonPrimary}
                className={classNames("__wab_instance", sty.buttonPrimary)}
                megaMenuLink={[]}
                text={(() => {
                  try {
                    return $queries.getHero.data.response.items[0].fields
                      .cta1Text;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return undefined;
                    }
                    throw e;
                  }
                })()}
                textArrowButton={true}
                url={(() => {
                  try {
                    return $queries.getHero.data.response.items[0].fields
                      .cta1Link;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "";
                    }
                    throw e;
                  }
                })()}
              />
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column___9FIqp)}>
            <div className={classNames(projectcss.all, sty.freeBox__nbck4)}>
              <div
                data-plasmic-name={"memberQuicklinks"}
                data-plasmic-override={overrides.memberQuicklinks}
                className={classNames(projectcss.all, sty.memberQuicklinks)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__y3Uph
                  )}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return $queries.getHero.data.response.items[0].fields
                          .cta2Text;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "Quick Links for Members";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__awY70)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__cJMde)}
                  >
                    {(_par =>
                      !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                      (() => {
                        try {
                          return $state.quicklinks;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return [];
                          }
                          throw e;
                        }
                      })()
                    ).map((__plasmic_item_0, __plasmic_idx_0) => {
                      const currentItem = __plasmic_item_0;
                      const currentIndex = __plasmic_idx_0;
                      return (
                        <PlasmicLink__
                          data-plasmic-name={"linkItem4"}
                          data-plasmic-override={overrides.linkItem4}
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            sty.linkItem4
                          )}
                          component={Link}
                          href={(() => {
                            try {
                              return currentItem.url;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                          key={currentIndex}
                          platform={"nextjs"}
                        >
                          <ChevronRight2Icon
                            data-plasmic-name={"svg"}
                            data-plasmic-override={overrides.svg}
                            className={classNames(projectcss.all, sty.svg)}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__em5RI
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return currentItem.label;
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "MyASSH";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                        </PlasmicLink__>
                      );
                    })}
                  </div>
                </div>
              </div>
              <PlasmicImg__
                data-plasmic-name={"img"}
                data-plasmic-override={overrides.img}
                alt={""}
                className={classNames(sty.img)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "250px"
                    : "100%"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"lazy"}
                src={(() => {
                  try {
                    return $queries.getHero.data.response.includes.Asset[0]
                      .fields.file.url;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return undefined;
                    }
                    throw e;
                  }
                })()}
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "columns",
    "frame12",
    "buttonPrimary",
    "memberQuicklinks",
    "linkItem4",
    "svg",
    "img"
  ],

  columns: [
    "columns",
    "frame12",
    "buttonPrimary",
    "memberQuicklinks",
    "linkItem4",
    "svg",
    "img"
  ],

  frame12: ["frame12", "buttonPrimary"],
  buttonPrimary: ["buttonPrimary"],
  memberQuicklinks: ["memberQuicklinks", "linkItem4", "svg"],
  linkItem4: ["linkItem4", "svg"],
  svg: ["svg"],
  img: ["img"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames:
            PlasmicSectionMidPageBannerWithQuicklinks__ArgProps,
          internalVariantPropNames:
            PlasmicSectionMidPageBannerWithQuicklinks__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSectionMidPageBannerWithQuicklinks__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSectionMidPageBannerWithQuicklinks";
  } else {
    func.displayName = `PlasmicSectionMidPageBannerWithQuicklinks.${nodeName}`;
  }
  return func;
}

export const PlasmicSectionMidPageBannerWithQuicklinks = Object.assign(
  // Top-level PlasmicSectionMidPageBannerWithQuicklinks renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    columns: makeNodeComponent("columns"),
    frame12: makeNodeComponent("frame12"),
    buttonPrimary: makeNodeComponent("buttonPrimary"),
    memberQuicklinks: makeNodeComponent("memberQuicklinks"),
    linkItem4: makeNodeComponent("linkItem4"),
    svg: makeNodeComponent("svg"),
    img: makeNodeComponent("img"),
    // Metadata about props expected for PlasmicSectionMidPageBannerWithQuicklinks
    internalVariantProps:
      PlasmicSectionMidPageBannerWithQuicklinks__VariantProps,
    internalArgProps: PlasmicSectionMidPageBannerWithQuicklinks__ArgProps
  }
);

export default PlasmicSectionMidPageBannerWithQuicklinks;
/* prettier-ignore-end */
