/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 34tvEQuyqfK98iGCjMbawB
// Component: _KLJDedJY247
import * as React from "react";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import ItemSectionTitleDescriptionItem from "../../ItemSectionTitleDescriptionItem"; // plasmic-import: jaOmCC9X_Oxf/component
import ButtonPrimary from "../../ButtonPrimary"; // plasmic-import: -2HqLDJqJBwh/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/styleTokensProvider
import { _useStyleTokens as useStyleTokens_antd_5_hostless } from "../antd_5_hostless/PlasmicStyleTokensProvider"; // plasmic-import: ohDidvG9XsCeFumugENU3J/styleTokensProvider
import { _useStyleTokens as useStyleTokens_plasmic_rich_components } from "../plasmic_rich_components/PlasmicStyleTokensProvider"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/projectcss
import sty from "./PlasmicComponentEventDetail.module.css"; // plasmic-import: _KLJDedJY247/css

createPlasmicElementProxy;

export const PlasmicComponentEventDetail__VariantProps = new Array();

export const PlasmicComponentEventDetail__ArgProps = new Array(
  "eventName",
  "registerUrl"
);

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicComponentEventDetail__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const styleTokensClassNames = _useStyleTokens();
  const styleTokensClassNames_antd_5_hostless =
    useStyleTokens_antd_5_hostless();
  const styleTokensClassNames_plasmic_rich_components =
    useStyleTokens_plasmic_rich_components();
  return (
    <div
      data-plasmic-name={"event"}
      data-plasmic-override={overrides.event}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        styleTokensClassNames_antd_5_hostless,
        styleTokensClassNames_plasmic_rich_components,
        sty.event
      )}
    >
      <ItemSectionTitleDescriptionItem
        data-plasmic-name={"itemSectionTitleDescriptionItem"}
        data-plasmic-override={overrides.itemSectionTitleDescriptionItem}
        className={classNames(
          "__wab_instance",
          sty.itemSectionTitleDescriptionItem
        )}
        descriptionSection={``}
        title={(() => {
          try {
            return $props.eventName;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return undefined;
            }
            throw e;
          }
        })()}
      />

      <div
        data-plasmic-name={"columns"}
        data-plasmic-override={overrides.columns}
        className={classNames(projectcss.all, sty.columns)}
      >
        <div className={classNames(projectcss.all, sty.column__jjRyM)}>
          <ButtonPrimary
            data-plasmic-name={"buttonPrimary"}
            data-plasmic-override={overrides.buttonPrimary}
            className={classNames("__wab_instance", sty.buttonPrimary)}
            secondaryInteractions={"secondary"}
            text={"Register"}
          />
        </div>
        <div className={classNames(projectcss.all, sty.column__s6VRh)} />
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  event: [
    "event",
    "itemSectionTitleDescriptionItem",
    "columns",
    "buttonPrimary"
  ],

  itemSectionTitleDescriptionItem: ["itemSectionTitleDescriptionItem"],
  columns: ["columns", "buttonPrimary"],
  buttonPrimary: ["buttonPrimary"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicComponentEventDetail__ArgProps,
          internalVariantPropNames: PlasmicComponentEventDetail__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicComponentEventDetail__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "event") {
    func.displayName = "PlasmicComponentEventDetail";
  } else {
    func.displayName = `PlasmicComponentEventDetail.${nodeName}`;
  }
  return func;
}

export const PlasmicComponentEventDetail = Object.assign(
  // Top-level PlasmicComponentEventDetail renders the root element
  makeNodeComponent("event"),
  {
    // Helper components rendering sub-elements
    itemSectionTitleDescriptionItem: makeNodeComponent(
      "itemSectionTitleDescriptionItem"
    ),
    columns: makeNodeComponent("columns"),
    buttonPrimary: makeNodeComponent("buttonPrimary"),
    // Metadata about props expected for PlasmicComponentEventDetail
    internalVariantProps: PlasmicComponentEventDetail__VariantProps,
    internalArgProps: PlasmicComponentEventDetail__ArgProps
  }
);

export default PlasmicComponentEventDetail;
/* prettier-ignore-end */
