/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 34tvEQuyqfK98iGCjMbawB
// Component: cfKosQT03FI3
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { usePlasmicDataOp } from "@plasmicapp/react-web/lib/data-sources";
import ItemAd from "../../ItemAd"; // plasmic-import: GN0Rszdi6Y-X/component
import SectionInternalHeroTitleSectionV2 from "../../SectionInternalHeroTitleSectionV2"; // plasmic-import: xL1xlGlXhY87/component
import HtmlContentfulHtmlLoader from "../../HtmlContentfulHtmlLoader"; // plasmic-import: yo4cxXaLxoOm/component
import BlockAsshMissionBlueBlock from "../../BlockAsshMissionBlueBlock"; // plasmic-import: oMTPDeBb_fES/component
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/projectcss
import sty from "./PlasmicMissionValuesVision.module.css"; // plasmic-import: cfKosQT03FI3/css

createPlasmicElementProxy;

export const PlasmicMissionValuesVision__VariantProps = new Array();

export const PlasmicMissionValuesVision__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMissionValuesVision__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  let [$queries, setDollarQueries] = React.useState({});
  const new$Queries = {
    getHtmlContent: usePlasmicDataOp(() => {
      return {
        sourceId: "tbVV8SR67UpQ6Z9zuPcDPB",
        opId: "10cec457-6ce7-415f-a3b0-329c11849ea6",
        userArgs: {},
        cacheKey: `plasmic.$.10cec457-6ce7-415f-a3b0-329c11849ea6.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);
    $queries = new$Queries;
  }
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">
          {PlasmicMissionValuesVision.pageMetadata.title}
        </title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicMissionValuesVision.pageMetadata.title}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicMissionValuesVision.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <ItemAd className={classNames("__wab_instance", sty.itemAd__jHbZc)} />
          <SectionInternalHeroTitleSectionV2
            data-plasmic-name={"sectionInternalHeroTitleSectionV2"}
            data-plasmic-override={overrides.sectionInternalHeroTitleSectionV2}
            className={classNames(
              "__wab_instance",
              sty.sectionInternalHeroTitleSectionV2
            )}
            title={"Hero: Mission Values Vision - Title Card"}
          />

          <div
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            className={classNames(projectcss.all, sty.freeBox)}
          >
            <HtmlContentfulHtmlLoader
              data-plasmic-name={"htmlContentfulHtmlLoader"}
              data-plasmic-override={overrides.htmlContentfulHtmlLoader}
              className={classNames(
                "__wab_instance",
                sty.htmlContentfulHtmlLoader
              )}
              title={"Mission Values Vision"}
            />
          </div>
          <ItemAd className={classNames("__wab_instance", sty.itemAd__lPsyf)} />
          <BlockAsshMissionBlueBlock
            data-plasmic-name={"blockAsshMissionBlueBlock"}
            data-plasmic-override={overrides.blockAsshMissionBlueBlock}
            className={classNames(
              "__wab_instance",
              sty.blockAsshMissionBlueBlock
            )}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "sectionInternalHeroTitleSectionV2",
    "freeBox",
    "htmlContentfulHtmlLoader",
    "blockAsshMissionBlueBlock"
  ],

  sectionInternalHeroTitleSectionV2: ["sectionInternalHeroTitleSectionV2"],
  freeBox: ["freeBox", "htmlContentfulHtmlLoader"],
  htmlContentfulHtmlLoader: ["htmlContentfulHtmlLoader"],
  blockAsshMissionBlueBlock: ["blockAsshMissionBlueBlock"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMissionValuesVision__ArgProps,
          internalVariantPropNames: PlasmicMissionValuesVision__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMissionValuesVision__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMissionValuesVision";
  } else {
    func.displayName = `PlasmicMissionValuesVision.${nodeName}`;
  }
  return func;
}

export const PlasmicMissionValuesVision = Object.assign(
  // Top-level PlasmicMissionValuesVision renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    sectionInternalHeroTitleSectionV2: makeNodeComponent(
      "sectionInternalHeroTitleSectionV2"
    ),
    freeBox: makeNodeComponent("freeBox"),
    htmlContentfulHtmlLoader: makeNodeComponent("htmlContentfulHtmlLoader"),
    blockAsshMissionBlueBlock: makeNodeComponent("blockAsshMissionBlueBlock"),
    // Metadata about props expected for PlasmicMissionValuesVision
    internalVariantProps: PlasmicMissionValuesVision__VariantProps,
    internalArgProps: PlasmicMissionValuesVision__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Mission, Values, Vision",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicMissionValuesVision;
/* prettier-ignore-end */
