/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 34tvEQuyqfK98iGCjMbawB
// Component: -PMY4qUfJ5kc
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import SectionAdPlaceholder from "../../SectionAdPlaceholder"; // plasmic-import: MWRaB-Trol6D/component
import SectionBreadcrumbs from "../../SectionBreadcrumbs"; // plasmic-import: TPxxugejEIaa/component
import SectionInternalHeroTitleSectionV2 from "../../SectionInternalHeroTitleSectionV2"; // plasmic-import: xL1xlGlXhY87/component
import ItemArticleCardItemWithDescription from "../../ItemArticleCardItemWithDescription"; // plasmic-import: m6xY8jJvNbEQ/component
import ItemSectionTitleDescriptionItem from "../../ItemSectionTitleDescriptionItem"; // plasmic-import: jaOmCC9X_Oxf/component
import HtmlContentfulHtmlLoader from "../../HtmlContentfulHtmlLoader"; // plasmic-import: yo4cxXaLxoOm/component
import ButtonPrimary from "../../ButtonPrimary"; // plasmic-import: -2HqLDJqJBwh/component
import BlockTanCtaBlock from "../../BlockTanCtaBlock"; // plasmic-import: YJsN7RAC0P0B/component
import BlockArticleCardList from "../../BlockArticleCardList"; // plasmic-import: HfgRxg6hxFsA/component
import SectionMidPageCtaSection from "../../SectionMidPageCtaSection"; // plasmic-import: yV5r8KM9AbUW/component
import SectionQuicklinksTable from "../../SectionQuicklinksTable"; // plasmic-import: dzBXgCr_C9up/component
import BlockAsshMissionBlueBlock from "../../BlockAsshMissionBlueBlock"; // plasmic-import: oMTPDeBb_fES/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/styleTokensProvider
import { _useStyleTokens as useStyleTokens_antd_5_hostless } from "../antd_5_hostless/PlasmicStyleTokensProvider"; // plasmic-import: ohDidvG9XsCeFumugENU3J/styleTokensProvider
import { _useStyleTokens as useStyleTokens_plasmic_rich_components } from "../plasmic_rich_components/PlasmicStyleTokensProvider"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/projectcss
import sty from "./PlasmicFellowships.module.css"; // plasmic-import: -PMY4qUfJ5kc/css

createPlasmicElementProxy;

export const PlasmicFellowships__VariantProps = new Array();

export const PlasmicFellowships__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFellowships__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const styleTokensClassNames = _useStyleTokens();
  const styleTokensClassNames_antd_5_hostless =
    useStyleTokens_antd_5_hostless();
  const styleTokensClassNames_plasmic_rich_components =
    useStyleTokens_plasmic_rich_components();
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicFellowships.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicFellowships.pageMetadata.title}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicFellowships.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            styleTokensClassNames_antd_5_hostless,
            styleTokensClassNames_plasmic_rich_components,
            sty.root
          )}
        >
          <SectionAdPlaceholder
            className={classNames(
              "__wab_instance",
              sty.sectionAdPlaceholder__y8IBo
            )}
          />

          <SectionBreadcrumbs
            data-plasmic-name={"sectionBreadcrumbs"}
            data-plasmic-override={overrides.sectionBreadcrumbs}
            className={classNames("__wab_instance", sty.sectionBreadcrumbs)}
            currentPagePath={(() => {
              try {
                return "/s" + $ctx.pagePath;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return undefined;
                }
                throw e;
              }
            })()}
          />

          <SectionInternalHeroTitleSectionV2
            data-plasmic-name={"sectionInternalHeroTitleSectionV2"}
            data-plasmic-override={overrides.sectionInternalHeroTitleSectionV2}
            className={classNames(
              "__wab_instance",
              sty.sectionInternalHeroTitleSectionV2
            )}
            title={"Hero: Fellowships - Title Card"}
          />

          <div className={classNames(projectcss.all, sty.freeBox__cfEmx)}>
            <div className={classNames(projectcss.all, sty.columns__gGwdw)}>
              <div className={classNames(projectcss.all, sty.column__fTKI)}>
                <ItemArticleCardItemWithDescription
                  articleTitle={"Fellowship Applications"}
                  className={classNames(
                    "__wab_instance",
                    sty.itemArticleCardItemWithDescription__l4Nh
                  )}
                  description={``}
                  heading={``}
                  linkUrl={"https://www.assh.org/applications/s/fellowshiphome"}
                  newTab={true}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___71FJm)}>
                <ItemArticleCardItemWithDescription
                  articleTitle={"Fellowship Directory"}
                  className={classNames(
                    "__wab_instance",
                    sty.itemArticleCardItemWithDescription__g1Yil
                  )}
                  description={``}
                  heading={``}
                  linkUrl={
                    "https://www.assh.org/applications/s/fellowshipdirectory"
                  }
                  newTab={true}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__wpgsv)}>
                <ItemArticleCardItemWithDescription
                  articleTitle={"HFDA Resources"}
                  className={classNames(
                    "__wab_instance",
                    sty.itemArticleCardItemWithDescription___6WGsx
                  )}
                  description={``}
                  heading={``}
                  linkUrl={"/s/education/fellowships/hfda"}
                  newTab={false}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__tCowm)}>
                <ItemArticleCardItemWithDescription
                  articleTitle={"Job Portal"}
                  className={classNames(
                    "__wab_instance",
                    sty.itemArticleCardItemWithDescription__bwYgo
                  )}
                  description={``}
                  heading={``}
                  linkUrl={"/s/membership/job-board"}
                />
              </div>
            </div>
            <ItemSectionTitleDescriptionItem
              className={classNames(
                "__wab_instance",
                sty.itemSectionTitleDescriptionItem__uAkIj
              )}
              descriptionSection={``}
              title={"Fellowship Resources"}
            />

            <HtmlContentfulHtmlLoader
              className={classNames(
                "__wab_instance",
                sty.htmlContentfulHtmlLoader__fuIr7
              )}
              title={"ASSH Resources for Fellowships"}
            />

            <div className={classNames(projectcss.all, sty.columns__fZuA3)}>
              <div className={classNames(projectcss.all, sty.column__nP3T3)}>
                <PlasmicImg__
                  data-plasmic-name={"img"}
                  data-plasmic-override={overrides.img}
                  alt={""}
                  className={classNames(sty.img)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  height={``}
                  loading={"lazy"}
                  src={
                    "https://images.ctfassets.net/k626j787po4v/2fJH1b0vQnBCrgKBrgSQSL/0f5ddf195d1f700268a683eeb2e95432/Fellowships-midpage-CTA.png"
                  }
                  width={"635"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__b08S)}>
                <HtmlContentfulHtmlLoader
                  className={classNames(
                    "__wab_instance",
                    sty.htmlContentfulHtmlLoader__bUgu2
                  )}
                  title={"Fellowships - Fellowship home"}
                />

                <ButtonPrimary
                  data-plasmic-name={"buttonPrimary"}
                  data-plasmic-override={overrides.buttonPrimary}
                  className={classNames("__wab_instance", sty.buttonPrimary)}
                  secondaryInteractions={"secondary"}
                  text={"Access the Fellowship System"}
                  url={"https://www.assh.org/applications/s/fellowshiphome"}
                />
              </div>
            </div>
            <BlockTanCtaBlock
              data-plasmic-name={"blockTanCtaBlock"}
              data-plasmic-override={overrides.blockTanCtaBlock}
              className={classNames("__wab_instance", sty.blockTanCtaBlock)}
              linkText={``}
              text2={``}
              title={"Tan CTA Block - Candidate Membership"}
            />

            <ItemSectionTitleDescriptionItem
              className={classNames(
                "__wab_instance",
                sty.itemSectionTitleDescriptionItem__fYkrs
              )}
              descriptionSection={``}
              title={"HFDA Resources for Fellows"}
            />

            <BlockArticleCardList
              data-plasmic-name={"blockArticleCardList"}
              data-plasmic-override={overrides.blockArticleCardList}
              className={classNames("__wab_instance", sty.blockArticleCardList)}
              name={"Fellowship: HFDA Fellow Resource Links"}
            />
          </div>
          <SectionMidPageCtaSection
            data-plasmic-name={"sectionMidPageCtaSection"}
            data-plasmic-override={overrides.sectionMidPageCtaSection}
            className={classNames(
              "__wab_instance",
              sty.sectionMidPageCtaSection
            )}
            title={"Fellowship - Mid-page CTA"}
          />

          <div className={classNames(projectcss.all, sty.freeBox__wZ5Ll)}>
            <SectionQuicklinksTable
              data-plasmic-name={"sectionQuicklinksTable"}
              data-plasmic-override={overrides.sectionQuicklinksTable}
              className={classNames(
                "__wab_instance",
                sty.sectionQuicklinksTable
              )}
              name={"Fellowships Quicklinks"}
            />
          </div>
          <SectionAdPlaceholder
            className={classNames(
              "__wab_instance",
              sty.sectionAdPlaceholder__rhAlN
            )}
          />

          <BlockAsshMissionBlueBlock
            data-plasmic-name={"blockAsshMissionBlueBlock"}
            data-plasmic-override={overrides.blockAsshMissionBlueBlock}
            className={classNames(
              "__wab_instance",
              sty.blockAsshMissionBlueBlock
            )}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "sectionBreadcrumbs",
    "sectionInternalHeroTitleSectionV2",
    "img",
    "buttonPrimary",
    "blockTanCtaBlock",
    "blockArticleCardList",
    "sectionMidPageCtaSection",
    "sectionQuicklinksTable",
    "blockAsshMissionBlueBlock"
  ],

  sectionBreadcrumbs: ["sectionBreadcrumbs"],
  sectionInternalHeroTitleSectionV2: ["sectionInternalHeroTitleSectionV2"],
  img: ["img"],
  buttonPrimary: ["buttonPrimary"],
  blockTanCtaBlock: ["blockTanCtaBlock"],
  blockArticleCardList: ["blockArticleCardList"],
  sectionMidPageCtaSection: ["sectionMidPageCtaSection"],
  sectionQuicklinksTable: ["sectionQuicklinksTable"],
  blockAsshMissionBlueBlock: ["blockAsshMissionBlueBlock"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFellowships__ArgProps,
          internalVariantPropNames: PlasmicFellowships__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFellowships__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFellowships";
  } else {
    func.displayName = `PlasmicFellowships.${nodeName}`;
  }
  return func;
}

export const PlasmicFellowships = Object.assign(
  // Top-level PlasmicFellowships renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    sectionBreadcrumbs: makeNodeComponent("sectionBreadcrumbs"),
    sectionInternalHeroTitleSectionV2: makeNodeComponent(
      "sectionInternalHeroTitleSectionV2"
    ),
    img: makeNodeComponent("img"),
    buttonPrimary: makeNodeComponent("buttonPrimary"),
    blockTanCtaBlock: makeNodeComponent("blockTanCtaBlock"),
    blockArticleCardList: makeNodeComponent("blockArticleCardList"),
    sectionMidPageCtaSection: makeNodeComponent("sectionMidPageCtaSection"),
    sectionQuicklinksTable: makeNodeComponent("sectionQuicklinksTable"),
    blockAsshMissionBlueBlock: makeNodeComponent("blockAsshMissionBlueBlock"),
    // Metadata about props expected for PlasmicFellowships
    internalVariantProps: PlasmicFellowships__VariantProps,
    internalArgProps: PlasmicFellowships__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Fellowships | Education | ASSH",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicFellowships;
/* prettier-ignore-end */
