/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 34tvEQuyqfK98iGCjMbawB
// Component: CVYojOYzb5cM
import * as React from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicLink as PlasmicLink__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  set as $stateSet,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/styleTokensProvider
import { _useStyleTokens as useStyleTokens_antd_5_hostless } from "../antd_5_hostless/PlasmicStyleTokensProvider"; // plasmic-import: ohDidvG9XsCeFumugENU3J/styleTokensProvider
import { _useStyleTokens as useStyleTokens_plasmic_rich_components } from "../plasmic_rich_components/PlasmicStyleTokensProvider"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/projectcss
import sty from "./PlasmicItemPagination.module.css"; // plasmic-import: CVYojOYzb5cM/css
import Icon9Icon from "./icons/PlasmicIcon__Icon9"; // plasmic-import: nipqwz5RnqR7/icon
import Container2Icon from "./icons/PlasmicIcon__Container2"; // plasmic-import: TKWn1DDMMFQp/icon
import ContainerIcon from "./icons/PlasmicIcon__Container"; // plasmic-import: LdpaQ2yuf9hP/icon

createPlasmicElementProxy;

export const PlasmicItemPagination__VariantProps = new Array();

export const PlasmicItemPagination__ArgProps = new Array(
  "totalRecords",
  "onTotalRecordsChange",
  "currentPage",
  "onCurrentPageChange",
  "pageSize",
  "onPageSizeChange"
);

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicItemPagination__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "totalRecords",
        type: "writable",
        variableType: "number",
        valueProp: "totalRecords",
        onChangeProp: "onTotalRecordsChange"
      },
      {
        path: "currentPage",
        type: "writable",
        variableType: "number",
        valueProp: "currentPage",
        onChangeProp: "onCurrentPageChange"
      },
      {
        path: "pageList",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return Array.from(
                { length: Math.ceil($state.totalRecords / $state.pageSize) },
                (_, index) => index + 1
              );
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return [];
              }
              throw e;
            }
          })()
      },
      {
        path: "pageSize",
        type: "writable",
        variableType: "number",
        valueProp: "pageSize",
        onChangeProp: "onPageSizeChange"
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  const styleTokensClassNames = _useStyleTokens();
  const styleTokensClassNames_antd_5_hostless =
    useStyleTokens_antd_5_hostless();
  const styleTokensClassNames_plasmic_rich_components =
    useStyleTokens_plasmic_rich_components();
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        styleTokensClassNames_antd_5_hostless,
        styleTokensClassNames_plasmic_rich_components,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"searchPagination"}
        data-plasmic-override={overrides.searchPagination}
        className={classNames(projectcss.all, sty.searchPagination)}
      >
        <div
          data-plasmic-name={"frame7"}
          data-plasmic-override={overrides.frame7}
          className={classNames(projectcss.all, sty.frame7)}
        >
          {false ? (
            <div
              data-plasmic-name={"navPillboxSmall"}
              data-plasmic-override={overrides.navPillboxSmall}
              className={classNames(projectcss.all, sty.navPillboxSmall)}
            >
              <div
                data-plasmic-name={"icon12X12"}
                data-plasmic-override={overrides.icon12X12}
                className={classNames(projectcss.all, sty.icon12X12)}
              >
                <div
                  data-plasmic-name={"container"}
                  data-plasmic-override={overrides.container}
                  className={classNames(projectcss.all, sty.container)}
                >
                  <Icon9Icon
                    className={classNames(projectcss.all, sty.svg__qVgc4)}
                    role={"img"}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"_1"}
                data-plasmic-override={overrides._1}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty._1
                )}
              >
                {"First"}
              </div>
              {false ? (
                <div
                  data-plasmic-name={"icon12X122"}
                  data-plasmic-override={overrides.icon12X122}
                  className={classNames(projectcss.all, sty.icon12X122)}
                >
                  <Container2Icon
                    className={classNames(projectcss.all, sty.svg__qmVf6)}
                    role={"img"}
                  />
                </div>
              ) : null}
            </div>
          ) : null}
          {(() => {
            try {
              return $state.currentPage !== 1;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <PlasmicLink__
              data-plasmic-name={"navPillboxSmall2"}
              data-plasmic-override={overrides.navPillboxSmall2}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.navPillboxSmall2
              )}
              component={Link}
              onClick={async event => {
                const $steps = {};
                $steps["updateCurrentPage"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: {
                          objRoot: $state,
                          variablePath: ["currentPage"]
                        },
                        operation: 0,
                        value: $state.currentPage - 1
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;
                        $stateSet(objRoot, variablePath, value);
                        return value;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateCurrentPage"] != null &&
                  typeof $steps["updateCurrentPage"] === "object" &&
                  typeof $steps["updateCurrentPage"].then === "function"
                ) {
                  $steps["updateCurrentPage"] = await $steps[
                    "updateCurrentPage"
                  ];
                }
                $steps["runCode"] = true
                  ? (() => {
                      const actionArgs = {
                        customFunction: async () => {
                          return (() => {
                            const element = document.getElementById("results");
                            if (element) {
                              return element.scrollIntoView();
                            }
                          })();
                        }
                      };
                      return (({ customFunction }) => {
                        return customFunction();
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["runCode"] != null &&
                  typeof $steps["runCode"] === "object" &&
                  typeof $steps["runCode"].then === "function"
                ) {
                  $steps["runCode"] = await $steps["runCode"];
                }
              }}
              platform={"nextjs"}
            >
              <div
                data-plasmic-name={"icon12X123"}
                data-plasmic-override={overrides.icon12X123}
                className={classNames(projectcss.all, sty.icon12X123)}
              >
                <ContainerIcon
                  className={classNames(projectcss.all, sty.svg__bCdkR)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"_2"}
                data-plasmic-override={overrides._2}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty._2
                )}
              >
                {"Previous"}
              </div>
              {false ? (
                <div
                  data-plasmic-name={"icon12X124"}
                  data-plasmic-override={overrides.icon12X124}
                  className={classNames(projectcss.all, sty.icon12X124)}
                >
                  <Container2Icon
                    className={classNames(projectcss.all, sty.svg__ik9Bq)}
                    role={"img"}
                  />
                </div>
              ) : null}
            </PlasmicLink__>
          ) : null}
        </div>
        <div
          data-plasmic-name={"frame6"}
          data-plasmic-override={overrides.frame6}
          className={classNames(projectcss.all, sty.frame6)}
        >
          {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
            (() => {
              try {
                return $state.pageList;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return [];
                }
                throw e;
              }
            })()
          ).map((__plasmic_item_0, __plasmic_idx_0) => {
            const currentItem = __plasmic_item_0;
            const currentIndex = __plasmic_idx_0;
            return (
              <PlasmicLink__
                data-plasmic-name={"navPillbox"}
                data-plasmic-override={overrides.navPillbox}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.navPillbox
                )}
                component={Link}
                key={currentIndex}
                onClick={async event => {
                  const $steps = {};
                  $steps["updateCurrentPage"] =
                    $state.currentPage !== currentItem
                      ? (() => {
                          const actionArgs = {
                            variable: {
                              objRoot: $state,
                              variablePath: ["currentPage"]
                            },
                            operation: 0,
                            value: currentItem
                          };
                          return (({
                            variable,
                            value,
                            startIndex,
                            deleteCount
                          }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;
                            $stateSet(objRoot, variablePath, value);
                            return value;
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                  if (
                    $steps["updateCurrentPage"] != null &&
                    typeof $steps["updateCurrentPage"] === "object" &&
                    typeof $steps["updateCurrentPage"].then === "function"
                  ) {
                    $steps["updateCurrentPage"] = await $steps[
                      "updateCurrentPage"
                    ];
                  }
                  $steps["runCode"] = true
                    ? (() => {
                        const actionArgs = {
                          customFunction: async () => {
                            return (() => {
                              const element =
                                document.getElementById("results");
                              if (element) {
                                return element.scrollIntoView();
                              }
                            })();
                          }
                        };
                        return (({ customFunction }) => {
                          return customFunction();
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["runCode"] != null &&
                    typeof $steps["runCode"] === "object" &&
                    typeof $steps["runCode"].then === "function"
                  ) {
                    $steps["runCode"] = await $steps["runCode"];
                  }
                }}
                platform={"nextjs"}
              >
                {(() => {
                  try {
                    return $state.currentPage !== currentItem;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return true;
                    }
                    throw e;
                  }
                })() ? (
                  <div
                    data-plasmic-name={"box"}
                    data-plasmic-override={overrides.box}
                    className={classNames(projectcss.all, sty.box)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mzPmm
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return currentItem;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "1";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </div>
                  </div>
                ) : null}
                {(() => {
                  try {
                    return $state.currentPage === currentItem;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return true;
                    }
                    throw e;
                  }
                })() ? (
                  <div
                    data-plasmic-name={"boxActive"}
                    data-plasmic-override={overrides.boxActive}
                    className={classNames(projectcss.all, sty.boxActive)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__s3JKt
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return currentItem;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "1";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </div>
                  </div>
                ) : null}
              </PlasmicLink__>
            );
          })}
        </div>
        <div
          data-plasmic-name={"frame1"}
          data-plasmic-override={overrides.frame1}
          className={classNames(projectcss.all, sty.frame1)}
        >
          {(() => {
            try {
              return $state.pageList.length !== $state.currentPage;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <PlasmicLink__
              data-plasmic-name={"navPillboxSmall8"}
              data-plasmic-override={overrides.navPillboxSmall8}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.navPillboxSmall8
              )}
              component={Link}
              onClick={async event => {
                const $steps = {};
                $steps["updateCurrentPage"] =
                  $state.currentPage < $state.pageList.length
                    ? (() => {
                        const actionArgs = {
                          variable: {
                            objRoot: $state,
                            variablePath: ["currentPage"]
                          },
                          operation: 0,
                          value: $state.currentPage + 1
                        };
                        return (({
                          variable,
                          value,
                          startIndex,
                          deleteCount
                        }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;
                          $stateSet(objRoot, variablePath, value);
                          return value;
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                if (
                  $steps["updateCurrentPage"] != null &&
                  typeof $steps["updateCurrentPage"] === "object" &&
                  typeof $steps["updateCurrentPage"].then === "function"
                ) {
                  $steps["updateCurrentPage"] = await $steps[
                    "updateCurrentPage"
                  ];
                }
                $steps["runCode"] = true
                  ? (() => {
                      const actionArgs = {
                        customFunction: async () => {
                          return (() => {
                            const element = document.getElementById("results");
                            if (element) {
                              return element.scrollIntoView();
                            }
                          })();
                        }
                      };
                      return (({ customFunction }) => {
                        return customFunction();
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["runCode"] != null &&
                  typeof $steps["runCode"] === "object" &&
                  typeof $steps["runCode"].then === "function"
                ) {
                  $steps["runCode"] = await $steps["runCode"];
                }
              }}
              platform={"nextjs"}
            >
              {false ? (
                <div
                  data-plasmic-name={"icon12X1213"}
                  data-plasmic-override={overrides.icon12X1213}
                  className={classNames(projectcss.all, sty.icon12X1213)}
                >
                  <ContainerIcon
                    className={classNames(projectcss.all, sty.svg__w8HbP)}
                    role={"img"}
                  />
                </div>
              ) : null}
              <div
                data-plasmic-name={"_7"}
                data-plasmic-override={overrides._7}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty._7
                )}
              >
                {"Next"}
              </div>
              <div
                data-plasmic-name={"icon12X1214"}
                data-plasmic-override={overrides.icon12X1214}
                className={classNames(projectcss.all, sty.icon12X1214)}
              >
                <Container2Icon
                  className={classNames(projectcss.all, sty.svg__mheBt)}
                  role={"img"}
                />
              </div>
            </PlasmicLink__>
          ) : null}
          {false ? (
            <div
              data-plasmic-name={"navPillboxSmall9"}
              data-plasmic-override={overrides.navPillboxSmall9}
              className={classNames(projectcss.all, sty.navPillboxSmall9)}
            >
              {false ? (
                <div
                  data-plasmic-name={"icon12X1215"}
                  data-plasmic-override={overrides.icon12X1215}
                  className={classNames(projectcss.all, sty.icon12X1215)}
                >
                  <ContainerIcon
                    className={classNames(projectcss.all, sty.svg___8SzxG)}
                    role={"img"}
                  />
                </div>
              ) : null}
              <div
                data-plasmic-name={"_8"}
                data-plasmic-override={overrides._8}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty._8
                )}
              >
                {"Last"}
              </div>
              <div
                data-plasmic-name={"icon12X1216"}
                data-plasmic-override={overrides.icon12X1216}
                className={classNames(projectcss.all, sty.icon12X1216)}
              >
                <div
                  data-plasmic-name={"container2"}
                  data-plasmic-override={overrides.container2}
                  className={classNames(projectcss.all, sty.container2)}
                >
                  <div
                    data-plasmic-name={"freeBox"}
                    data-plasmic-override={overrides.freeBox}
                    className={classNames(projectcss.all, sty.freeBox)}
                  >
                    <Icon9Icon
                      className={classNames(projectcss.all, sty.svg__wLvz)}
                      role={"img"}
                    />
                  </div>
                </div>
              </div>
            </div>
          ) : null}
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "searchPagination",
    "frame7",
    "navPillboxSmall",
    "icon12X12",
    "container",
    "_1",
    "icon12X122",
    "navPillboxSmall2",
    "icon12X123",
    "_2",
    "icon12X124",
    "frame6",
    "navPillbox",
    "box",
    "boxActive",
    "frame1",
    "navPillboxSmall8",
    "icon12X1213",
    "_7",
    "icon12X1214",
    "navPillboxSmall9",
    "icon12X1215",
    "_8",
    "icon12X1216",
    "container2",
    "freeBox"
  ],

  searchPagination: [
    "searchPagination",
    "frame7",
    "navPillboxSmall",
    "icon12X12",
    "container",
    "_1",
    "icon12X122",
    "navPillboxSmall2",
    "icon12X123",
    "_2",
    "icon12X124",
    "frame6",
    "navPillbox",
    "box",
    "boxActive",
    "frame1",
    "navPillboxSmall8",
    "icon12X1213",
    "_7",
    "icon12X1214",
    "navPillboxSmall9",
    "icon12X1215",
    "_8",
    "icon12X1216",
    "container2",
    "freeBox"
  ],

  frame7: [
    "frame7",
    "navPillboxSmall",
    "icon12X12",
    "container",
    "_1",
    "icon12X122",
    "navPillboxSmall2",
    "icon12X123",
    "_2",
    "icon12X124"
  ],

  navPillboxSmall: [
    "navPillboxSmall",
    "icon12X12",
    "container",
    "_1",
    "icon12X122"
  ],

  icon12X12: ["icon12X12", "container"],
  container: ["container"],
  _1: ["_1"],
  icon12X122: ["icon12X122"],
  navPillboxSmall2: ["navPillboxSmall2", "icon12X123", "_2", "icon12X124"],
  icon12X123: ["icon12X123"],
  _2: ["_2"],
  icon12X124: ["icon12X124"],
  frame6: ["frame6", "navPillbox", "box", "boxActive"],
  navPillbox: ["navPillbox", "box", "boxActive"],
  box: ["box"],
  boxActive: ["boxActive"],
  frame1: [
    "frame1",
    "navPillboxSmall8",
    "icon12X1213",
    "_7",
    "icon12X1214",
    "navPillboxSmall9",
    "icon12X1215",
    "_8",
    "icon12X1216",
    "container2",
    "freeBox"
  ],

  navPillboxSmall8: ["navPillboxSmall8", "icon12X1213", "_7", "icon12X1214"],
  icon12X1213: ["icon12X1213"],
  _7: ["_7"],
  icon12X1214: ["icon12X1214"],
  navPillboxSmall9: [
    "navPillboxSmall9",
    "icon12X1215",
    "_8",
    "icon12X1216",
    "container2",
    "freeBox"
  ],

  icon12X1215: ["icon12X1215"],
  _8: ["_8"],
  icon12X1216: ["icon12X1216", "container2", "freeBox"],
  container2: ["container2", "freeBox"],
  freeBox: ["freeBox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicItemPagination__ArgProps,
          internalVariantPropNames: PlasmicItemPagination__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicItemPagination__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicItemPagination";
  } else {
    func.displayName = `PlasmicItemPagination.${nodeName}`;
  }
  return func;
}

export const PlasmicItemPagination = Object.assign(
  // Top-level PlasmicItemPagination renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    searchPagination: makeNodeComponent("searchPagination"),
    frame7: makeNodeComponent("frame7"),
    navPillboxSmall: makeNodeComponent("navPillboxSmall"),
    icon12X12: makeNodeComponent("icon12X12"),
    container: makeNodeComponent("container"),
    _1: makeNodeComponent("_1"),
    icon12X122: makeNodeComponent("icon12X122"),
    navPillboxSmall2: makeNodeComponent("navPillboxSmall2"),
    icon12X123: makeNodeComponent("icon12X123"),
    _2: makeNodeComponent("_2"),
    icon12X124: makeNodeComponent("icon12X124"),
    frame6: makeNodeComponent("frame6"),
    navPillbox: makeNodeComponent("navPillbox"),
    box: makeNodeComponent("box"),
    boxActive: makeNodeComponent("boxActive"),
    frame1: makeNodeComponent("frame1"),
    navPillboxSmall8: makeNodeComponent("navPillboxSmall8"),
    icon12X1213: makeNodeComponent("icon12X1213"),
    _7: makeNodeComponent("_7"),
    icon12X1214: makeNodeComponent("icon12X1214"),
    navPillboxSmall9: makeNodeComponent("navPillboxSmall9"),
    icon12X1215: makeNodeComponent("icon12X1215"),
    _8: makeNodeComponent("_8"),
    icon12X1216: makeNodeComponent("icon12X1216"),
    container2: makeNodeComponent("container2"),
    freeBox: makeNodeComponent("freeBox"),
    // Metadata about props expected for PlasmicItemPagination
    internalVariantProps: PlasmicItemPagination__VariantProps,
    internalArgProps: PlasmicItemPagination__ArgProps
  }
);

export default PlasmicItemPagination;
/* prettier-ignore-end */
