/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 34tvEQuyqfK98iGCjMbawB
// Component: buA5LBYO5-1M
import * as React from "react";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { usePlasmicDataOp } from "@plasmicapp/react-web/lib/data-sources";
import ItemEventCardItemInfoOnly from "../../ItemEventCardItemInfoOnly"; // plasmic-import: UPjziaoo_XKO/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/styleTokensProvider
import { _useStyleTokens as useStyleTokens_antd_5_hostless } from "../antd_5_hostless/PlasmicStyleTokensProvider"; // plasmic-import: ohDidvG9XsCeFumugENU3J/styleTokensProvider
import { _useStyleTokens as useStyleTokens_plasmic_rich_components } from "../plasmic_rich_components/PlasmicStyleTokensProvider"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/projectcss
import sty from "./PlasmicComponentFutureEventList.module.css"; // plasmic-import: buA5LBYO5-1M/css

createPlasmicElementProxy;

export const PlasmicComponentFutureEventList__VariantProps = new Array();

export const PlasmicComponentFutureEventList__ArgProps = new Array(
  "limit",
  "onLimitChange2",
  "type",
  "onTypeChange",
  "eventIdNe",
  "onEventIdNeChange"
);

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicComponentFutureEventList__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  let [$queries, setDollarQueries] = React.useState({});
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "limit",
        type: "writable",
        variableType: "text",
        valueProp: "limit",
        onChangeProp: "onLimitChange2"
      },
      {
        path: "type",
        type: "writable",
        variableType: "text",
        valueProp: "type",
        onChangeProp: "onTypeChange"
      },
      {
        path: "eventIdNe",
        type: "writable",
        variableType: "text",
        valueProp: "eventIdNe",
        onChangeProp: "onEventIdNeChange"
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $refs
  });
  const new$Queries = {
    getEvents: usePlasmicDataOp(() => {
      return {
        sourceId: "tbVV8SR67UpQ6Z9zuPcDPB",
        opId: "7900b06b-4f42-454a-a179-1909ef868b0b",
        userArgs: {
          params: [
            $state.limit,
            (() => {
              const date = new Date(Date.now() - 24 * 60 * 60 * 1000);
              return date.toISOString().split(".")[0] + "Z";
            })(),
            $state.type,
            $state.eventIdNe
          ]
        },
        cacheKey: `plasmic.$.7900b06b-4f42-454a-a179-1909ef868b0b.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);
    $queries = new$Queries;
  }
  const styleTokensClassNames = _useStyleTokens();
  const styleTokensClassNames_antd_5_hostless =
    useStyleTokens_antd_5_hostless();
  const styleTokensClassNames_plasmic_rich_components =
    useStyleTokens_plasmic_rich_components();
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        styleTokensClassNames_antd_5_hostless,
        styleTokensClassNames_plasmic_rich_components,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"frame4"}
        data-plasmic-override={overrides.frame4}
        className={classNames(projectcss.all, sty.frame4)}
      >
        {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
          (() => {
            try {
              return $queries.getEvents.data.response.items;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return [];
              }
              throw e;
            }
          })()
        ).map((__plasmic_item_0, __plasmic_idx_0) => {
          const currentItem = __plasmic_item_0;
          const currentIndex = __plasmic_idx_0;
          return (
            <div
              data-plasmic-name={"eventsCard"}
              data-plasmic-override={overrides.eventsCard}
              className={classNames(
                projectcss.all,
                sty.eventsCard,
                "event-card-item"
              )}
              key={currentIndex}
            >
              <div
                data-plasmic-name={"content2"}
                data-plasmic-override={overrides.content2}
                className={classNames(projectcss.all, sty.content2, ``)}
              >
                <ItemEventCardItemInfoOnly
                  data-plasmic-name={"itemEventCardItemInfoOnly"}
                  data-plasmic-override={overrides.itemEventCardItemInfoOnly}
                  className={classNames(
                    "__wab_instance",
                    sty.itemEventCardItemInfoOnly
                  )}
                  dates={(() => {
                    try {
                      return currentItem.fields.dates;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                  location={(() => {
                    try {
                      return currentItem.fields.locationName;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                  registerUrl={(() => {
                    try {
                      return currentItem.fields.infoLink;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                  title={(() => {
                    try {
                      return currentItem.fields.title;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                />
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "frame4",
    "eventsCard",
    "content2",
    "itemEventCardItemInfoOnly"
  ],

  frame4: ["frame4", "eventsCard", "content2", "itemEventCardItemInfoOnly"],
  eventsCard: ["eventsCard", "content2", "itemEventCardItemInfoOnly"],
  content2: ["content2", "itemEventCardItemInfoOnly"],
  itemEventCardItemInfoOnly: ["itemEventCardItemInfoOnly"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicComponentFutureEventList__ArgProps,
          internalVariantPropNames:
            PlasmicComponentFutureEventList__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicComponentFutureEventList__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicComponentFutureEventList";
  } else {
    func.displayName = `PlasmicComponentFutureEventList.${nodeName}`;
  }
  return func;
}

export const PlasmicComponentFutureEventList = Object.assign(
  // Top-level PlasmicComponentFutureEventList renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    frame4: makeNodeComponent("frame4"),
    eventsCard: makeNodeComponent("eventsCard"),
    content2: makeNodeComponent("content2"),
    itemEventCardItemInfoOnly: makeNodeComponent("itemEventCardItemInfoOnly"),
    // Metadata about props expected for PlasmicComponentFutureEventList
    internalVariantProps: PlasmicComponentFutureEventList__VariantProps,
    internalArgProps: PlasmicComponentFutureEventList__ArgProps
  }
);

export default PlasmicComponentFutureEventList;
/* prettier-ignore-end */
