/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 34tvEQuyqfK98iGCjMbawB
// Component: oYnNfUl2bMfC
import * as React from "react";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { usePlasmicDataOp } from "@plasmicapp/react-web/lib/data-sources";
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/styleTokensProvider
import { _useStyleTokens as useStyleTokens_antd_5_hostless } from "../antd_5_hostless/PlasmicStyleTokensProvider"; // plasmic-import: ohDidvG9XsCeFumugENU3J/styleTokensProvider
import { _useStyleTokens as useStyleTokens_plasmic_rich_components } from "../plasmic_rich_components/PlasmicStyleTokensProvider"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/projectcss
import sty from "./PlasmicItemNewsArticle.module.css"; // plasmic-import: oYnNfUl2bMfC/css

createPlasmicElementProxy;

export const PlasmicItemNewsArticle__VariantProps = new Array();

export const PlasmicItemNewsArticle__ArgProps = new Array("internalName");

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicItemNewsArticle__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          internalName: "Perspectives: October 2023 - The WALANT Technique"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  let [$queries, setDollarQueries] = React.useState({});
  const new$Queries = {
    getContent: usePlasmicDataOp(() => {
      return {
        sourceId: "tbVV8SR67UpQ6Z9zuPcDPB",
        opId: "61b37066-7bed-4596-8e56-fc542eb8b34e",
        userArgs: {
          params: [$props.internalName]
        },
        cacheKey: `plasmic.$.61b37066-7bed-4596-8e56-fc542eb8b34e.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);
    $queries = new$Queries;
  }
  const styleTokensClassNames = _useStyleTokens();
  const styleTokensClassNames_antd_5_hostless =
    useStyleTokens_antd_5_hostless();
  const styleTokensClassNames_plasmic_rich_components =
    useStyleTokens_plasmic_rich_components();
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        styleTokensClassNames_antd_5_hostless,
        styleTokensClassNames_plasmic_rich_components,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__aoP4T)}>
        <h1
          data-plasmic-name={"h1"}
          data-plasmic-override={overrides.h1}
          className={classNames(
            projectcss.all,
            projectcss.h1,
            projectcss.__wab_text,
            sty.h1
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return $queries.getContent.data.response.items[0].fields.title;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "You won't believe what happens next.";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </h1>
        <h2
          data-plasmic-name={"subtitle"}
          data-plasmic-override={overrides.subtitle}
          className={classNames(
            projectcss.all,
            projectcss.h2,
            projectcss.__wab_text,
            sty.subtitle
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return $queries.getContent.data.response.items[0].fields
                  .subtitle;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "You won't believe what happens next.";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </h2>
        <div
          data-plasmic-name={"dateField"}
          data-plasmic-override={overrides.dateField}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.dateField
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return $queries.getContent.data.response.items[0].fields.date;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </div>
      </div>
      {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
        (() => {
          try {
            return $queries.getContent.data.response.items[0].fields.authors;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return [];
            }
            throw e;
          }
        })()
      ).map((__plasmic_item_0, __plasmic_idx_0) => {
        const currentItem = __plasmic_item_0;
        const currentIndex = __plasmic_idx_0;
        return (
          <div
            className={classNames(projectcss.all, sty.freeBox__rAqmS)}
            key={currentIndex}
          >
            <div
              data-plasmic-name={"authors"}
              data-plasmic-override={overrides.authors}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.authors
              )}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return currentItem;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__esdN9)}>
              <Embed
                data-plasmic-name={"embedHtml"}
                data-plasmic-override={overrides.embedHtml}
                className={classNames("__wab_instance", sty.embedHtml)}
                code={(() => {
                  try {
                    return $queries.getContent.data.response.items[0].fields
                      .bodyContent;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "<div>Paste your embed code via the right sidebar</div>";
                    }
                    throw e;
                  }
                })()}
              />
            </div>
          </div>
        );
      })}
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "h1", "subtitle", "dateField", "authors", "embedHtml"],
  h1: ["h1"],
  subtitle: ["subtitle"],
  dateField: ["dateField"],
  authors: ["authors"],
  embedHtml: ["embedHtml"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicItemNewsArticle__ArgProps,
          internalVariantPropNames: PlasmicItemNewsArticle__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicItemNewsArticle__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicItemNewsArticle";
  } else {
    func.displayName = `PlasmicItemNewsArticle.${nodeName}`;
  }
  return func;
}

export const PlasmicItemNewsArticle = Object.assign(
  // Top-level PlasmicItemNewsArticle renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h1: makeNodeComponent("h1"),
    subtitle: makeNodeComponent("subtitle"),
    dateField: makeNodeComponent("dateField"),
    authors: makeNodeComponent("authors"),
    embedHtml: makeNodeComponent("embedHtml"),
    // Metadata about props expected for PlasmicItemNewsArticle
    internalVariantProps: PlasmicItemNewsArticle__VariantProps,
    internalArgProps: PlasmicItemNewsArticle__ArgProps
  }
);

export default PlasmicItemNewsArticle;
/* prettier-ignore-end */
