/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 34tvEQuyqfK98iGCjMbawB
// Component: usMTMpuc29Th
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateStateOnChangeProp,
  generateStateValueProp,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { usePlasmicDataOp } from "@plasmicapp/react-web/lib/data-sources";
import SectionAdPlaceholder from "../../SectionAdPlaceholder"; // plasmic-import: MWRaB-Trol6D/component
import SectionInternalHeroTitleSectionV2 from "../../SectionInternalHeroTitleSectionV2"; // plasmic-import: xL1xlGlXhY87/component
import SectionNewsListItems from "../../SectionNewsListItems"; // plasmic-import: 5-ayHp8nG4OH/component
import ItemPagination from "../../ItemPagination"; // plasmic-import: CVYojOYzb5cM/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/styleTokensProvider
import { _useStyleTokens as useStyleTokens_antd_5_hostless } from "../antd_5_hostless/PlasmicStyleTokensProvider"; // plasmic-import: ohDidvG9XsCeFumugENU3J/styleTokensProvider
import { _useStyleTokens as useStyleTokens_plasmic_rich_components } from "../plasmic_rich_components/PlasmicStyleTokensProvider"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/projectcss
import sty from "./PlasmicMemberNews.module.css"; // plasmic-import: usMTMpuc29Th/css

createPlasmicElementProxy;

export const PlasmicMemberNews__VariantProps = new Array();

export const PlasmicMemberNews__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMemberNews__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  let [$queries, setDollarQueries] = React.useState({});
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "pageSize",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 10
      },
      {
        path: "itemPagination.totalRecords",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $queries.getContent.data.response.total;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return 1;
              }
              throw e;
            }
          })()
      },
      {
        path: "itemPagination.currentPage",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 3
      },
      {
        path: "itemPagination.pageSize",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $state.pageSize;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return 10;
              }
              throw e;
            }
          })()
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $refs
  });
  const new$Queries = {
    getContent: usePlasmicDataOp(() => {
      return {
        sourceId: "tbVV8SR67UpQ6Z9zuPcDPB",
        opId: "cf46b8c6-7429-4b19-996b-bee00a11514e",
        userArgs: {
          params: [
            $state.pageSize,
            $state.pageSize * ($state.itemPagination.currentPage - 1)
          ]
        },
        cacheKey: `plasmic.$.cf46b8c6-7429-4b19-996b-bee00a11514e.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);
    $queries = new$Queries;
  }
  const styleTokensClassNames = _useStyleTokens();
  const styleTokensClassNames_antd_5_hostless =
    useStyleTokens_antd_5_hostless();
  const styleTokensClassNames_plasmic_rich_components =
    useStyleTokens_plasmic_rich_components();
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicMemberNews.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicMemberNews.pageMetadata.title}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicMemberNews.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            styleTokensClassNames_antd_5_hostless,
            styleTokensClassNames_plasmic_rich_components,
            sty.root
          )}
        >
          <SectionAdPlaceholder
            data-plasmic-name={"sectionAdPlaceholder"}
            data-plasmic-override={overrides.sectionAdPlaceholder}
            className={classNames("__wab_instance", sty.sectionAdPlaceholder)}
          />

          <SectionInternalHeroTitleSectionV2
            data-plasmic-name={"sectionInternalHeroTitleSectionV2"}
            data-plasmic-override={overrides.sectionInternalHeroTitleSectionV2}
            className={classNames(
              "__wab_instance",
              sty.sectionInternalHeroTitleSectionV2
            )}
            title={"Hero: Member News - Title Card"}
          />

          {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
            (() => {
              try {
                return $queries.getContent.data.response.items;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return [];
                }
                throw e;
              }
            })()
          ).map((__plasmic_item_0, __plasmic_idx_0) => {
            const currentItem = __plasmic_item_0;
            const currentIndex = __plasmic_idx_0;
            return (
              <div
                className={classNames(projectcss.all, sty.freeBox__jp4Sc)}
                id={"results"}
                key={currentIndex}
              >
                <SectionNewsListItems
                  data-plasmic-name={"sectionNewsListItems"}
                  data-plasmic-override={overrides.sectionNewsListItems}
                  className={classNames(
                    "__wab_instance",
                    sty.sectionNewsListItems
                  )}
                  summary={(() => {
                    try {
                      return currentItem.fields.summary;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                  title={(() => {
                    try {
                      return currentItem.fields.title;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                  url={(() => {
                    try {
                      return currentItem.fields.urlPath;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                />
              </div>
            );
          })}
          <div className={classNames(projectcss.all, sty.freeBox__fqNtJ)}>
            <ItemPagination
              data-plasmic-name={"itemPagination"}
              data-plasmic-override={overrides.itemPagination}
              className={classNames("__wab_instance", sty.itemPagination)}
              currentPage={generateStateValueProp($state, [
                "itemPagination",
                "currentPage"
              ])}
              onCurrentPageChange={async (...eventArgs) => {
                generateStateOnChangeProp($state, [
                  "itemPagination",
                  "currentPage"
                ]).apply(null, eventArgs);
                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              onPageSizeChange={async (...eventArgs) => {
                generateStateOnChangeProp($state, [
                  "itemPagination",
                  "pageSize"
                ]).apply(null, eventArgs);
                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              onTotalRecordsChange={async (...eventArgs) => {
                generateStateOnChangeProp($state, [
                  "itemPagination",
                  "totalRecords"
                ]).apply(null, eventArgs);
                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              pageSize={generateStateValueProp($state, [
                "itemPagination",
                "pageSize"
              ])}
              totalRecords={generateStateValueProp($state, [
                "itemPagination",
                "totalRecords"
              ])}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "sectionAdPlaceholder",
    "sectionInternalHeroTitleSectionV2",
    "sectionNewsListItems",
    "itemPagination"
  ],

  sectionAdPlaceholder: ["sectionAdPlaceholder"],
  sectionInternalHeroTitleSectionV2: ["sectionInternalHeroTitleSectionV2"],
  sectionNewsListItems: ["sectionNewsListItems"],
  itemPagination: ["itemPagination"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMemberNews__ArgProps,
          internalVariantPropNames: PlasmicMemberNews__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMemberNews__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMemberNews";
  } else {
    func.displayName = `PlasmicMemberNews.${nodeName}`;
  }
  return func;
}

export const PlasmicMemberNews = Object.assign(
  // Top-level PlasmicMemberNews renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    sectionAdPlaceholder: makeNodeComponent("sectionAdPlaceholder"),
    sectionInternalHeroTitleSectionV2: makeNodeComponent(
      "sectionInternalHeroTitleSectionV2"
    ),
    sectionNewsListItems: makeNodeComponent("sectionNewsListItems"),
    itemPagination: makeNodeComponent("itemPagination"),
    // Metadata about props expected for PlasmicMemberNews
    internalVariantProps: PlasmicMemberNews__VariantProps,
    internalArgProps: PlasmicMemberNews__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Member News | News & Publications | ASSH",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicMemberNews;
/* prettier-ignore-end */
