/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 34tvEQuyqfK98iGCjMbawB
// Component: 4sVxlULRtaDO
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import SectionInternalHeroTitleSectionV2 from "../../SectionInternalHeroTitleSectionV2"; // plasmic-import: xL1xlGlXhY87/component
import ItemSectionTitleDescriptionItem from "../../ItemSectionTitleDescriptionItem"; // plasmic-import: jaOmCC9X_Oxf/component
import HtmlContentfulHtmlLoader from "../../HtmlContentfulHtmlLoader"; // plasmic-import: yo4cxXaLxoOm/component
import BlockArticleCardList from "../../BlockArticleCardList"; // plasmic-import: HfgRxg6hxFsA/component
import SectionMidPageCtaSection from "../../SectionMidPageCtaSection"; // plasmic-import: yV5r8KM9AbUW/component
import ItemArticleCardItemWithDescription from "../../ItemArticleCardItemWithDescription"; // plasmic-import: m6xY8jJvNbEQ/component
import SectionQuicklinksTable from "../../SectionQuicklinksTable"; // plasmic-import: dzBXgCr_C9up/component
import SectionAdPlaceholder from "../../SectionAdPlaceholder"; // plasmic-import: MWRaB-Trol6D/component
import BlockAsshMissionBlueBlock from "../../BlockAsshMissionBlueBlock"; // plasmic-import: oMTPDeBb_fES/component
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/projectcss
import sty from "./PlasmicForResidentsAndFellows.module.css"; // plasmic-import: 4sVxlULRtaDO/css

createPlasmicElementProxy;

export const PlasmicForResidentsAndFellows__VariantProps = new Array();

export const PlasmicForResidentsAndFellows__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicForResidentsAndFellows__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">
          {PlasmicForResidentsAndFellows.pageMetadata.title}
        </title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicForResidentsAndFellows.pageMetadata.title}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicForResidentsAndFellows.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <SectionInternalHeroTitleSectionV2
            data-plasmic-name={"sectionInternalHeroTitleSectionV2"}
            data-plasmic-override={overrides.sectionInternalHeroTitleSectionV2}
            className={classNames(
              "__wab_instance",
              sty.sectionInternalHeroTitleSectionV2
            )}
            title={"Hero: For R&F - Title Card"}
          />

          <ItemSectionTitleDescriptionItem
            data-plasmic-name={"itemSectionTitleDescriptionItem"}
            data-plasmic-override={overrides.itemSectionTitleDescriptionItem}
            className={classNames(
              "__wab_instance",
              sty.itemSectionTitleDescriptionItem
            )}
            descriptionSection={``}
            title={"How ASSH Supports Trainees"}
          />

          <div className={classNames(projectcss.all, sty.columns__tHanH)}>
            <div className={classNames(projectcss.all, sty.column___6Ft7Y)}>
              <HtmlContentfulHtmlLoader
                data-plasmic-name={"htmlContentfulHtmlLoader"}
                data-plasmic-override={overrides.htmlContentfulHtmlLoader}
                className={classNames(
                  "__wab_instance",
                  sty.htmlContentfulHtmlLoader
                )}
                title={"How ASSH Supports Trainees"}
              />
            </div>
          </div>
          <BlockArticleCardList
            data-plasmic-name={"blockArticleCardList"}
            data-plasmic-override={overrides.blockArticleCardList}
            className={classNames("__wab_instance", sty.blockArticleCardList)}
            name={"For Surgeons: Resident & Fellow Resources"}
          />

          <SectionMidPageCtaSection
            data-plasmic-name={"sectionMidPageCtaSection"}
            data-plasmic-override={overrides.sectionMidPageCtaSection}
            className={classNames(
              "__wab_instance",
              sty.sectionMidPageCtaSection
            )}
            title={"For R&F - Mid-page CTA"}
          />

          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.columns__wlX9N)}
          >
            <div className={classNames(projectcss.all, sty.column__js182)}>
              <ItemArticleCardItemWithDescription
                articleTitle={"Candidate Member"}
                className={classNames(
                  "__wab_instance",
                  sty.itemArticleCardItemWithDescription___3BJe4
                )}
                description={
                  "Surgeons within 3 years of completing residency, current fellows, and practicing surgeons up to 5 years."
                }
                heading={"Membership Type"}
                linkUrl={"/membership/candidate"}
              />
            </div>
            <div className={classNames(projectcss.all, sty.column___2JMt)}>
              <ItemArticleCardItemWithDescription
                articleTitle={"Active Member"}
                className={classNames(
                  "__wab_instance",
                  sty.itemArticleCardItemWithDescription__fgPfc
                )}
                description={
                  "U.S. hand surgeons who have passed the CAQ and\u00a0Canadian hand surgeons\u00a0certified by the Royal College."
                }
                heading={"Membership Type"}
                linkUrl={"/membership/active"}
              />
            </div>
            <div className={classNames(projectcss.all, sty.column__ctKpB)}>
              <ItemArticleCardItemWithDescription
                articleTitle={"Membership Benefits"}
                className={classNames(
                  "__wab_instance",
                  sty.itemArticleCardItemWithDescription__yiVq
                )}
                description={``}
                heading={"Membership Info"}
                linkUrl={"/membership/benefits"}
              />
            </div>
            <div className={classNames(projectcss.all, sty.column__zIb7)}>
              <ItemArticleCardItemWithDescription
                articleTitle={"Young International Member"}
                className={classNames(
                  "__wab_instance",
                  sty.itemArticleCardItemWithDescription__kqTpV
                )}
                description={
                  "Surgeons\u00a0within 5\u00a0years of completing\u00a0a post-graduate program in disorders of the upper limbs."
                }
                heading={"Membership Type"}
                linkUrl={"/membership/young-international"}
              />
            </div>
            <div className={classNames(projectcss.all, sty.column__ebrVe)}>
              <ItemArticleCardItemWithDescription
                articleTitle={"Affiliate Member"}
                className={classNames(
                  "__wab_instance",
                  sty.itemArticleCardItemWithDescription___4S9W6
                )}
                description={
                  "Fully licensed allied healthcare professionals (i.e., hand therapist, OT, PT, PA, NP or RN)."
                }
                heading={"Membership Type"}
                linkUrl={"/membership/affiliate"}
              />
            </div>
            <div className={classNames(projectcss.all, sty.column__hjq8K)}>
              <ItemArticleCardItemWithDescription
                articleTitle={"Supporting Member"}
                className={classNames(
                  "__wab_instance",
                  sty.itemArticleCardItemWithDescription__nliQ
                )}
                description={
                  "Non-surgeons who have contributed to the understanding and/or treatment of disorders of the upper limbs."
                }
                heading={"Membership Type"}
                linkUrl={"/membership/supporting-member"}
              />
            </div>
          </Stack__>
          <SectionQuicklinksTable
            data-plasmic-name={"sectionQuicklinksTable"}
            data-plasmic-override={overrides.sectionQuicklinksTable}
            className={classNames("__wab_instance", sty.sectionQuicklinksTable)}
            columns={"_3Column"}
            name={"For R&F Quicklinks"}
          />

          <SectionAdPlaceholder
            data-plasmic-name={"sectionAdPlaceholder"}
            data-plasmic-override={overrides.sectionAdPlaceholder}
            className={classNames("__wab_instance", sty.sectionAdPlaceholder)}
          />

          <BlockAsshMissionBlueBlock
            data-plasmic-name={"blockAsshMissionBlueBlock"}
            data-plasmic-override={overrides.blockAsshMissionBlueBlock}
            className={classNames(
              "__wab_instance",
              sty.blockAsshMissionBlueBlock
            )}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "sectionInternalHeroTitleSectionV2",
    "itemSectionTitleDescriptionItem",
    "htmlContentfulHtmlLoader",
    "blockArticleCardList",
    "sectionMidPageCtaSection",
    "sectionQuicklinksTable",
    "sectionAdPlaceholder",
    "blockAsshMissionBlueBlock"
  ],

  sectionInternalHeroTitleSectionV2: ["sectionInternalHeroTitleSectionV2"],
  itemSectionTitleDescriptionItem: ["itemSectionTitleDescriptionItem"],
  htmlContentfulHtmlLoader: ["htmlContentfulHtmlLoader"],
  blockArticleCardList: ["blockArticleCardList"],
  sectionMidPageCtaSection: ["sectionMidPageCtaSection"],
  sectionQuicklinksTable: ["sectionQuicklinksTable"],
  sectionAdPlaceholder: ["sectionAdPlaceholder"],
  blockAsshMissionBlueBlock: ["blockAsshMissionBlueBlock"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicForResidentsAndFellows__ArgProps,
          internalVariantPropNames: PlasmicForResidentsAndFellows__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicForResidentsAndFellows__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicForResidentsAndFellows";
  } else {
    func.displayName = `PlasmicForResidentsAndFellows.${nodeName}`;
  }
  return func;
}

export const PlasmicForResidentsAndFellows = Object.assign(
  // Top-level PlasmicForResidentsAndFellows renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    sectionInternalHeroTitleSectionV2: makeNodeComponent(
      "sectionInternalHeroTitleSectionV2"
    ),
    itemSectionTitleDescriptionItem: makeNodeComponent(
      "itemSectionTitleDescriptionItem"
    ),
    htmlContentfulHtmlLoader: makeNodeComponent("htmlContentfulHtmlLoader"),
    blockArticleCardList: makeNodeComponent("blockArticleCardList"),
    sectionMidPageCtaSection: makeNodeComponent("sectionMidPageCtaSection"),
    sectionQuicklinksTable: makeNodeComponent("sectionQuicklinksTable"),
    sectionAdPlaceholder: makeNodeComponent("sectionAdPlaceholder"),
    blockAsshMissionBlueBlock: makeNodeComponent("blockAsshMissionBlueBlock"),
    // Metadata about props expected for PlasmicForResidentsAndFellows
    internalVariantProps: PlasmicForResidentsAndFellows__VariantProps,
    internalArgProps: PlasmicForResidentsAndFellows__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "For Residents & Fellows",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicForResidentsAndFellows;
/* prettier-ignore-end */
