/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 34tvEQuyqfK98iGCjMbawB
// Component: ekmlUmTm1Njf
import * as React from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicLink as PlasmicLink__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import ButtonPrimary from "../../ButtonPrimary"; // plasmic-import: -2HqLDJqJBwh/component
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/styleTokensProvider
import { _useStyleTokens as useStyleTokens_antd_5_hostless } from "../antd_5_hostless/PlasmicStyleTokensProvider"; // plasmic-import: ohDidvG9XsCeFumugENU3J/styleTokensProvider
import { _useStyleTokens as useStyleTokens_plasmic_rich_components } from "../plasmic_rich_components/PlasmicStyleTokensProvider"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/projectcss
import sty from "./PlasmicSectionMyDashboard.module.css"; // plasmic-import: ekmlUmTm1Njf/css
import Line32Icon from "./icons/PlasmicIcon__Line32"; // plasmic-import: RL7-l-m3w1ha/icon
import ContainerIcon from "./icons/PlasmicIcon__Container"; // plasmic-import: LdpaQ2yuf9hP/icon
import Container4Icon from "./icons/PlasmicIcon__Container4"; // plasmic-import: aJfVCHtjgUkz/icon
import Container2Icon from "./icons/PlasmicIcon__Container2"; // plasmic-import: TKWn1DDMMFQp/icon

createPlasmicElementProxy;

export const PlasmicSectionMyDashboard__VariantProps = new Array();

export const PlasmicSectionMyDashboard__ArgProps = new Array(
  "meetingAttendance",
  "yearsMembership",
  "educationActivities",
  "committees",
  "ePubs",
  "givingLevel",
  "totalAnnualDonations",
  "accountMemberType",
  "averageAccountTypeDonations",
  "fahsViews",
  "percentMostViewed",
  "userdetails"
);

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSectionMyDashboard__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          userdetails: {
            Webrole: "test",
            userDashboard: {
              yearsOfMembership: 0,
              totalDonations: 0,
              meetingAttendance: 0,
              FASHViews: 0,
              FAHSMostViewed: 0,
              educationActivities: 0,
              cards: [
                {
                  name: "myepubs",
                  cardItems: [
                    {
                      name: "Epub - Fractures and Dislocations of the Hand and Fingers",
                      id: "a13j000000091zjAAA"
                    },
                    {
                      name: "Epub - Fractures and Dislocations of the Hand and Fingers",
                      id: "a13j000000091zjAAA"
                    },
                    {
                      name: "Epub - Fractures and Dislocations of the Hand and Fingers",
                      id: "a13j000000091zjAAA"
                    }
                  ]
                }
              ],

              averageMemberDonation: 0
            },
            donationLevel: null,
            Photo:
              "https://handsociety.s3.amazonaws.com/members_photo/profile/127185.png",
            PersonTitle: "Director of Finger, Hand, Wrist and Shoulder Surgery",
            Name: null,
            MemberType: "Active Member",
            JoinDate: "01/01/1999",
            Fullname: "Dr. Thomas F Crain",
            FirstName: "Thomas",
            FAHSEligible: true,
            Designation: "MD",
            ASSHID: ""
          }
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const styleTokensClassNames = _useStyleTokens();
  const styleTokensClassNames_antd_5_hostless =
    useStyleTokens_antd_5_hostless();
  const styleTokensClassNames_plasmic_rich_components =
    useStyleTokens_plasmic_rich_components();
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        styleTokensClassNames_antd_5_hostless,
        styleTokensClassNames_plasmic_rich_components,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"dashboard"}
        data-plasmic-override={overrides.dashboard}
        className={classNames(projectcss.all, sty.dashboard)}
      >
        <div
          data-plasmic-name={"topSummaryBar"}
          data-plasmic-override={overrides.topSummaryBar}
          className={classNames(projectcss.all, sty.topSummaryBar)}
        >
          <div className={classNames(projectcss.all, sty.column__l5DGx)}>
            <div
              data-plasmic-name={"frame11"}
              data-plasmic-override={overrides.frame11}
              className={classNames(projectcss.all, sty.frame11)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vIxkV
                )}
              >
                <React.Fragment>
                  {(() => {
                    try {
                      return $props.yearsMembership;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "0";
                      }
                      throw e;
                    }
                  })()}
                </React.Fragment>
              </div>
              <Line32Icon
                className={classNames(projectcss.all, sty.svg__uwwzn)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cxkkf
                )}
              >
                {"Years of Membership"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__tWuG7)}>
            <div
              data-plasmic-name={"frame12"}
              data-plasmic-override={overrides.frame12}
              className={classNames(projectcss.all, sty.frame12)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mg9BO
                )}
              >
                <React.Fragment>
                  {(() => {
                    try {
                      return $props.meetingAttendance;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "0";
                      }
                      throw e;
                    }
                  })()}
                </React.Fragment>
              </div>
              <Line32Icon
                className={classNames(projectcss.all, sty.svg__pmoFo)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qySw3
                )}
              >
                {"Meeting Attendance"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__pTzmK)}>
            <div
              data-plasmic-name={"frame13"}
              data-plasmic-override={overrides.frame13}
              className={classNames(projectcss.all, sty.frame13)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ic03S
                )}
              >
                <React.Fragment>
                  {(() => {
                    try {
                      return $props.educationActivities;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "0";
                      }
                      throw e;
                    }
                  })()}
                </React.Fragment>
              </div>
              <Line32Icon
                className={classNames(projectcss.all, sty.svg___2XMqm)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ch8Rt
                )}
              >
                {"Education Activities"}
              </div>
            </div>
          </div>
        </div>
        <div
          data-plasmic-name={"secondRow"}
          data-plasmic-override={overrides.secondRow}
          className={classNames(projectcss.all, sty.secondRow)}
        >
          <div className={classNames(projectcss.all, sty.column__vcUz2)}>
            <div
              data-plasmic-name={"committeesSection"}
              data-plasmic-override={overrides.committeesSection}
              className={classNames(projectcss.all, sty.committeesSection)}
            >
              <div
                data-plasmic-name={"frame26"}
                data-plasmic-override={overrides.frame26}
                className={classNames(projectcss.all, sty.frame26)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pRvj
                  )}
                >
                  {"My Committees"}
                </div>
                <div
                  data-plasmic-name={"frame14"}
                  data-plasmic-override={overrides.frame14}
                  className={classNames(projectcss.all, sty.frame14)}
                >
                  {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
                    (() => {
                      try {
                        return $props.committees;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return [];
                        }
                        throw e;
                      }
                    })()
                  ).map((__plasmic_item_0, __plasmic_idx_0) => {
                    const currentItem = __plasmic_item_0;
                    const currentIndex = __plasmic_idx_0;
                    return (
                      <PlasmicLink__
                        data-plasmic-name={"navMenu6"}
                        data-plasmic-override={overrides.navMenu6}
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.navMenu6
                        )}
                        component={Link}
                        href={(() => {
                          try {
                            return currentItem.url;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()}
                        key={currentIndex}
                        platform={"nextjs"}
                      >
                        <div
                          data-plasmic-name={"navigationItem10"}
                          data-plasmic-override={overrides.navigationItem10}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.navigationItem10
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return currentItem.name;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "Courses & Webinars Committee";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                        {(() => {
                          try {
                            return currentItem.status === "current";
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return true;
                            }
                            throw e;
                          }
                        })() ? (
                          <div
                            data-plasmic-name={"currentPill"}
                            data-plasmic-override={overrides.currentPill}
                            className={classNames(
                              projectcss.all,
                              sty.currentPill
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__xWKc
                              )}
                            >
                              {"Current"}
                            </div>
                          </div>
                        ) : null}
                        {(() => {
                          try {
                            return currentItem.status === "future";
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return true;
                            }
                            throw e;
                          }
                        })() ? (
                          <div
                            data-plasmic-name={"futurePill"}
                            data-plasmic-override={overrides.futurePill}
                            className={classNames(
                              projectcss.all,
                              sty.futurePill
                            )}
                          >
                            <div
                              data-plasmic-name={"future"}
                              data-plasmic-override={overrides.future}
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.future
                              )}
                            >
                              {"Future"}
                            </div>
                          </div>
                        ) : null}
                        {(() => {
                          try {
                            return currentItem.status === "past";
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return true;
                            }
                            throw e;
                          }
                        })() ? (
                          <div
                            data-plasmic-name={"pastPill"}
                            data-plasmic-override={overrides.pastPill}
                            className={classNames(projectcss.all, sty.pastPill)}
                          >
                            <div
                              data-plasmic-name={"future2"}
                              data-plasmic-override={overrides.future2}
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.future2
                              )}
                            >
                              {"Past"}
                            </div>
                          </div>
                        ) : null}
                      </PlasmicLink__>
                    );
                  })}
                </div>
              </div>
              <div
                data-plasmic-name={"navItemSimple5"}
                data-plasmic-override={overrides.navItemSimple5}
                className={classNames(projectcss.all, sty.navItemSimple5)}
              >
                <ButtonPrimary
                  className={classNames(
                    "__wab_instance",
                    sty.buttonPrimary__soG0J
                  )}
                  text={"All Committees"}
                  textArrowButton={true}
                  url={"/s/committees"}
                />
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__aSe3G)}>
            <div
              data-plasmic-name={"ePubsSection"}
              data-plasmic-override={overrides.ePubsSection}
              className={classNames(projectcss.all, sty.ePubsSection)}
            >
              <div
                data-plasmic-name={"frame27"}
                data-plasmic-override={overrides.frame27}
                className={classNames(projectcss.all, sty.frame27)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8KyfT
                  )}
                >
                  {"My EPubs"}
                </div>
                <div
                  data-plasmic-name={"frame28"}
                  data-plasmic-override={overrides.frame28}
                  className={classNames(projectcss.all, sty.frame28)}
                >
                  {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
                    (() => {
                      try {
                        return $props.ePubs;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return [];
                        }
                        throw e;
                      }
                    })()
                  ).map((__plasmic_item_0, __plasmic_idx_0) => {
                    const currentItem = __plasmic_item_0;
                    const currentIndex = __plasmic_idx_0;
                    return (
                      <PlasmicLink__
                        data-plasmic-name={"navMenu8"}
                        data-plasmic-override={overrides.navMenu8}
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.navMenu8
                        )}
                        component={Link}
                        href={(() => {
                          try {
                            return $props.ePubs;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()}
                        key={currentIndex}
                        platform={"nextjs"}
                      >
                        {false ? (
                          <div
                            data-plasmic-name={"icon12X1229"}
                            data-plasmic-override={overrides.icon12X1229}
                            className={classNames(
                              projectcss.all,
                              sty.icon12X1229
                            )}
                          >
                            <ContainerIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__hdgHw
                              )}
                              role={"img"}
                            />
                          </div>
                        ) : null}
                        <div
                          data-plasmic-name={"navigationItem13"}
                          data-plasmic-override={overrides.navigationItem13}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.navigationItem13
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return currentItem.name;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "e-Book - Advanced Concepts of Hand Pathology & Surgery";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                        {false ? (
                          <div
                            data-plasmic-name={"icon12X1230"}
                            data-plasmic-override={overrides.icon12X1230}
                            className={classNames(
                              projectcss.all,
                              sty.icon12X1230
                            )}
                          >
                            <Container4Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__mSeBn
                              )}
                              role={"img"}
                            />
                          </div>
                        ) : null}
                      </PlasmicLink__>
                    );
                  })}
                </div>
              </div>
              <div
                data-plasmic-name={"navItemSimple6"}
                data-plasmic-override={overrides.navItemSimple6}
                className={classNames(projectcss.all, sty.navItemSimple6)}
              >
                <ButtonPrimary
                  className={classNames(
                    "__wab_instance",
                    sty.buttonPrimary__mY297
                  )}
                  text={"ASSH Store"}
                  textArrowButton={true}
                  url={"https://www.assh.org/store"}
                />
              </div>
            </div>
          </div>
        </div>
        <div
          data-plasmic-name={"thirdRow"}
          data-plasmic-override={overrides.thirdRow}
          className={classNames(projectcss.all, sty.thirdRow)}
        >
          <div className={classNames(projectcss.all, sty.column__whsUw)}>
            <div
              data-plasmic-name={"donationsSection"}
              data-plasmic-override={overrides.donationsSection}
              className={classNames(projectcss.all, sty.donationsSection)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bwz1Z
                )}
              >
                {"My Donations"}
              </div>
              <div
                data-plasmic-name={"frame71"}
                data-plasmic-override={overrides.frame71}
                className={classNames(projectcss.all, sty.frame71)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rgoOk
                  )}
                >
                  {"Donation Level:"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___5RKtj,
                    (() => {
                      try {
                        return "giving-" + $props.givingLevel.toLowerCase();
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()
                  )}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return $props.givingLevel;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "Gold";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
              </div>
              <div
                data-plasmic-name={"frame29"}
                data-plasmic-override={overrides.frame29}
                className={classNames(projectcss.all, sty.frame29)}
              >
                <div
                  data-plasmic-name={"frame65"}
                  data-plasmic-override={overrides.frame65}
                  className={classNames(projectcss.all, sty.frame65)}
                >
                  <div
                    data-plasmic-name={"frame30"}
                    data-plasmic-override={overrides.frame30}
                    className={classNames(projectcss.all, sty.frame30)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___5Z0Hh
                      )}
                    >
                      {"My Total Annual Donations"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___2LrXo
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return new Intl.NumberFormat("en-US", {
                              style: "currency",
                              currency: "USD",
                              minimumFractionDigits: 0
                            }).format($props.totalAnnualDonations);
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "0";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"group15"}
                    data-plasmic-override={overrides.group15}
                    className={classNames(projectcss.all, sty.group15)}
                  >
                    <div
                      data-plasmic-name={"percContainer"}
                      data-plasmic-override={overrides.percContainer}
                      className={classNames(projectcss.all, sty.percContainer)}
                    />

                    <Embed
                      data-plasmic-name={"percFilled"}
                      data-plasmic-override={overrides.percFilled}
                      className={classNames("__wab_instance", sty.percFilled)}
                      code={(() => {
                        try {
                          return (
                            '<div class="percentage-bar" style="width: ' +
                            Math.round(
                              ($props.totalAnnualDonations /
                                $props.averageAccountTypeDonations) *
                                100
                            ) +
                            '%"></div>'
                          );
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "";
                          }
                          throw e;
                        }
                      })()}
                    />
                  </div>
                </div>
                <div
                  data-plasmic-name={"frame66"}
                  data-plasmic-override={overrides.frame66}
                  className={classNames(projectcss.all, sty.frame66)}
                >
                  <div
                    data-plasmic-name={"frame33"}
                    data-plasmic-override={overrides.frame33}
                    className={classNames(projectcss.all, sty.frame33)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xs6Mk
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return (
                              "Average " +
                              $props.accountMemberType +
                              " Total Annual Donations"
                            );
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "Average Active Member Total Annual Donations";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wL3B
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return new Intl.NumberFormat("en-US", {
                              style: "currency",
                              currency: "USD",
                              minimumFractionDigits: 0
                            }).format($props.averageAccountTypeDonations);
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "0";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"rectangle41"}
                    data-plasmic-override={overrides.rectangle41}
                    className={classNames(projectcss.all, sty.rectangle41)}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"frame34"}
                data-plasmic-override={overrides.frame34}
                className={classNames(projectcss.all, sty.frame34)}
              >
                <div
                  data-plasmic-name={"buttonHighlight3"}
                  data-plasmic-override={overrides.buttonHighlight3}
                  className={classNames(projectcss.all, sty.buttonHighlight3)}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"icon12X1237"}
                      data-plasmic-override={overrides.icon12X1237}
                      className={classNames(projectcss.all, sty.icon12X1237)}
                    >
                      <ContainerIcon
                        className={classNames(projectcss.all, sty.svg___1PJgx)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    data-plasmic-name={"text3"}
                    data-plasmic-override={overrides.text3}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text3
                    )}
                  >
                    {"Make a Donation"}
                  </div>
                  {false ? (
                    <div
                      data-plasmic-name={"icon12X1238"}
                      data-plasmic-override={overrides.icon12X1238}
                      className={classNames(projectcss.all, sty.icon12X1238)}
                    >
                      <Container2Icon
                        className={classNames(projectcss.all, sty.svg__vjbYa)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                </div>
                <div
                  data-plasmic-name={"buttonDefault2"}
                  data-plasmic-override={overrides.buttonDefault2}
                  className={classNames(projectcss.all, sty.buttonDefault2)}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"icon12X1239"}
                      data-plasmic-override={overrides.icon12X1239}
                      className={classNames(projectcss.all, sty.icon12X1239)}
                    >
                      <ContainerIcon
                        className={classNames(projectcss.all, sty.svg__s1N16)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    data-plasmic-name={"text4"}
                    data-plasmic-override={overrides.text4}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text4
                    )}
                  >
                    {"Ways to Give"}
                  </div>
                  {false ? (
                    <div
                      data-plasmic-name={"icon12X1240"}
                      data-plasmic-override={overrides.icon12X1240}
                      className={classNames(projectcss.all, sty.icon12X1240)}
                    >
                      <Container2Icon
                        className={classNames(projectcss.all, sty.svg__tO8Wk)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                </div>
              </div>
              <div
                data-plasmic-name={"navItemSimple7"}
                data-plasmic-override={overrides.navItemSimple7}
                className={classNames(projectcss.all, sty.navItemSimple7)}
              >
                <ButtonPrimary
                  className={classNames(
                    "__wab_instance",
                    sty.buttonPrimary__lRztd
                  )}
                  text={"My Donation History"}
                  textArrowButton={true}
                  url={"/s/my-account/donation-history"}
                />
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__hOzIh)}>
            <div
              data-plasmic-name={"fahsSection"}
              data-plasmic-override={overrides.fahsSection}
              className={classNames(projectcss.all, sty.fahsSection)}
            >
              <div
                data-plasmic-name={"frame31"}
                data-plasmic-override={overrides.frame31}
                className={classNames(projectcss.all, sty.frame31)}
              >
                <div
                  data-plasmic-name={"frame32"}
                  data-plasmic-override={overrides.frame32}
                  className={classNames(projectcss.all, sty.frame32)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___28WC
                    )}
                  >
                    {"Find a Hand Surgeon"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"frame35"}
                  data-plasmic-override={overrides.frame35}
                  className={classNames(projectcss.all, sty.frame35)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___4NUyV
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $props.fahsViews;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "0";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                  <Line32Icon
                    className={classNames(projectcss.all, sty.svg__haPrv)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kO7Px
                    )}
                  >
                    {"Profile Views"}
                  </div>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eqmK
                  )}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return (
                          $props.percentMostViewed +
                          "% most viewed in your area code"
                        );
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "64% most viewed in your area code";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
              </div>
              <div
                data-plasmic-name={"navItemSimple8"}
                data-plasmic-override={overrides.navItemSimple8}
                className={classNames(projectcss.all, sty.navItemSimple8)}
              >
                <ButtonPrimary
                  className={classNames(
                    "__wab_instance",
                    sty.buttonPrimary__oY4Cb
                  )}
                  text={"View Find a Hand Surgeon"}
                  textArrowButton={true}
                  url={"https://www.assh.org/handcare/fahs"}
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "dashboard",
    "topSummaryBar",
    "frame11",
    "frame12",
    "frame13",
    "secondRow",
    "committeesSection",
    "frame26",
    "frame14",
    "navMenu6",
    "navigationItem10",
    "currentPill",
    "futurePill",
    "future",
    "pastPill",
    "future2",
    "navItemSimple5",
    "ePubsSection",
    "frame27",
    "frame28",
    "navMenu8",
    "icon12X1229",
    "navigationItem13",
    "icon12X1230",
    "navItemSimple6",
    "thirdRow",
    "donationsSection",
    "frame71",
    "frame29",
    "frame65",
    "frame30",
    "group15",
    "percContainer",
    "percFilled",
    "frame66",
    "frame33",
    "rectangle41",
    "frame34",
    "buttonHighlight3",
    "icon12X1237",
    "text3",
    "icon12X1238",
    "buttonDefault2",
    "icon12X1239",
    "text4",
    "icon12X1240",
    "navItemSimple7",
    "fahsSection",
    "frame31",
    "frame32",
    "frame35",
    "navItemSimple8"
  ],

  dashboard: [
    "dashboard",
    "topSummaryBar",
    "frame11",
    "frame12",
    "frame13",
    "secondRow",
    "committeesSection",
    "frame26",
    "frame14",
    "navMenu6",
    "navigationItem10",
    "currentPill",
    "futurePill",
    "future",
    "pastPill",
    "future2",
    "navItemSimple5",
    "ePubsSection",
    "frame27",
    "frame28",
    "navMenu8",
    "icon12X1229",
    "navigationItem13",
    "icon12X1230",
    "navItemSimple6",
    "thirdRow",
    "donationsSection",
    "frame71",
    "frame29",
    "frame65",
    "frame30",
    "group15",
    "percContainer",
    "percFilled",
    "frame66",
    "frame33",
    "rectangle41",
    "frame34",
    "buttonHighlight3",
    "icon12X1237",
    "text3",
    "icon12X1238",
    "buttonDefault2",
    "icon12X1239",
    "text4",
    "icon12X1240",
    "navItemSimple7",
    "fahsSection",
    "frame31",
    "frame32",
    "frame35",
    "navItemSimple8"
  ],

  topSummaryBar: ["topSummaryBar", "frame11", "frame12", "frame13"],
  frame11: ["frame11"],
  frame12: ["frame12"],
  frame13: ["frame13"],
  secondRow: [
    "secondRow",
    "committeesSection",
    "frame26",
    "frame14",
    "navMenu6",
    "navigationItem10",
    "currentPill",
    "futurePill",
    "future",
    "pastPill",
    "future2",
    "navItemSimple5",
    "ePubsSection",
    "frame27",
    "frame28",
    "navMenu8",
    "icon12X1229",
    "navigationItem13",
    "icon12X1230",
    "navItemSimple6"
  ],

  committeesSection: [
    "committeesSection",
    "frame26",
    "frame14",
    "navMenu6",
    "navigationItem10",
    "currentPill",
    "futurePill",
    "future",
    "pastPill",
    "future2",
    "navItemSimple5"
  ],

  frame26: [
    "frame26",
    "frame14",
    "navMenu6",
    "navigationItem10",
    "currentPill",
    "futurePill",
    "future",
    "pastPill",
    "future2"
  ],

  frame14: [
    "frame14",
    "navMenu6",
    "navigationItem10",
    "currentPill",
    "futurePill",
    "future",
    "pastPill",
    "future2"
  ],

  navMenu6: [
    "navMenu6",
    "navigationItem10",
    "currentPill",
    "futurePill",
    "future",
    "pastPill",
    "future2"
  ],

  navigationItem10: ["navigationItem10"],
  currentPill: ["currentPill"],
  futurePill: ["futurePill", "future"],
  future: ["future"],
  pastPill: ["pastPill", "future2"],
  future2: ["future2"],
  navItemSimple5: ["navItemSimple5"],
  ePubsSection: [
    "ePubsSection",
    "frame27",
    "frame28",
    "navMenu8",
    "icon12X1229",
    "navigationItem13",
    "icon12X1230",
    "navItemSimple6"
  ],

  frame27: [
    "frame27",
    "frame28",
    "navMenu8",
    "icon12X1229",
    "navigationItem13",
    "icon12X1230"
  ],

  frame28: [
    "frame28",
    "navMenu8",
    "icon12X1229",
    "navigationItem13",
    "icon12X1230"
  ],

  navMenu8: ["navMenu8", "icon12X1229", "navigationItem13", "icon12X1230"],
  icon12X1229: ["icon12X1229"],
  navigationItem13: ["navigationItem13"],
  icon12X1230: ["icon12X1230"],
  navItemSimple6: ["navItemSimple6"],
  thirdRow: [
    "thirdRow",
    "donationsSection",
    "frame71",
    "frame29",
    "frame65",
    "frame30",
    "group15",
    "percContainer",
    "percFilled",
    "frame66",
    "frame33",
    "rectangle41",
    "frame34",
    "buttonHighlight3",
    "icon12X1237",
    "text3",
    "icon12X1238",
    "buttonDefault2",
    "icon12X1239",
    "text4",
    "icon12X1240",
    "navItemSimple7",
    "fahsSection",
    "frame31",
    "frame32",
    "frame35",
    "navItemSimple8"
  ],

  donationsSection: [
    "donationsSection",
    "frame71",
    "frame29",
    "frame65",
    "frame30",
    "group15",
    "percContainer",
    "percFilled",
    "frame66",
    "frame33",
    "rectangle41",
    "frame34",
    "buttonHighlight3",
    "icon12X1237",
    "text3",
    "icon12X1238",
    "buttonDefault2",
    "icon12X1239",
    "text4",
    "icon12X1240",
    "navItemSimple7"
  ],

  frame71: ["frame71"],
  frame29: [
    "frame29",
    "frame65",
    "frame30",
    "group15",
    "percContainer",
    "percFilled",
    "frame66",
    "frame33",
    "rectangle41"
  ],

  frame65: ["frame65", "frame30", "group15", "percContainer", "percFilled"],
  frame30: ["frame30"],
  group15: ["group15", "percContainer", "percFilled"],
  percContainer: ["percContainer"],
  percFilled: ["percFilled"],
  frame66: ["frame66", "frame33", "rectangle41"],
  frame33: ["frame33"],
  rectangle41: ["rectangle41"],
  frame34: [
    "frame34",
    "buttonHighlight3",
    "icon12X1237",
    "text3",
    "icon12X1238",
    "buttonDefault2",
    "icon12X1239",
    "text4",
    "icon12X1240"
  ],

  buttonHighlight3: ["buttonHighlight3", "icon12X1237", "text3", "icon12X1238"],
  icon12X1237: ["icon12X1237"],
  text3: ["text3"],
  icon12X1238: ["icon12X1238"],
  buttonDefault2: ["buttonDefault2", "icon12X1239", "text4", "icon12X1240"],
  icon12X1239: ["icon12X1239"],
  text4: ["text4"],
  icon12X1240: ["icon12X1240"],
  navItemSimple7: ["navItemSimple7"],
  fahsSection: [
    "fahsSection",
    "frame31",
    "frame32",
    "frame35",
    "navItemSimple8"
  ],

  frame31: ["frame31", "frame32", "frame35"],
  frame32: ["frame32"],
  frame35: ["frame35"],
  navItemSimple8: ["navItemSimple8"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSectionMyDashboard__ArgProps,
          internalVariantPropNames: PlasmicSectionMyDashboard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSectionMyDashboard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSectionMyDashboard";
  } else {
    func.displayName = `PlasmicSectionMyDashboard.${nodeName}`;
  }
  return func;
}

export const PlasmicSectionMyDashboard = Object.assign(
  // Top-level PlasmicSectionMyDashboard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    dashboard: makeNodeComponent("dashboard"),
    topSummaryBar: makeNodeComponent("topSummaryBar"),
    frame11: makeNodeComponent("frame11"),
    frame12: makeNodeComponent("frame12"),
    frame13: makeNodeComponent("frame13"),
    secondRow: makeNodeComponent("secondRow"),
    committeesSection: makeNodeComponent("committeesSection"),
    frame26: makeNodeComponent("frame26"),
    frame14: makeNodeComponent("frame14"),
    navMenu6: makeNodeComponent("navMenu6"),
    navigationItem10: makeNodeComponent("navigationItem10"),
    currentPill: makeNodeComponent("currentPill"),
    futurePill: makeNodeComponent("futurePill"),
    future: makeNodeComponent("future"),
    pastPill: makeNodeComponent("pastPill"),
    future2: makeNodeComponent("future2"),
    navItemSimple5: makeNodeComponent("navItemSimple5"),
    ePubsSection: makeNodeComponent("ePubsSection"),
    frame27: makeNodeComponent("frame27"),
    frame28: makeNodeComponent("frame28"),
    navMenu8: makeNodeComponent("navMenu8"),
    icon12X1229: makeNodeComponent("icon12X1229"),
    navigationItem13: makeNodeComponent("navigationItem13"),
    icon12X1230: makeNodeComponent("icon12X1230"),
    navItemSimple6: makeNodeComponent("navItemSimple6"),
    thirdRow: makeNodeComponent("thirdRow"),
    donationsSection: makeNodeComponent("donationsSection"),
    frame71: makeNodeComponent("frame71"),
    frame29: makeNodeComponent("frame29"),
    frame65: makeNodeComponent("frame65"),
    frame30: makeNodeComponent("frame30"),
    group15: makeNodeComponent("group15"),
    percContainer: makeNodeComponent("percContainer"),
    percFilled: makeNodeComponent("percFilled"),
    frame66: makeNodeComponent("frame66"),
    frame33: makeNodeComponent("frame33"),
    rectangle41: makeNodeComponent("rectangle41"),
    frame34: makeNodeComponent("frame34"),
    buttonHighlight3: makeNodeComponent("buttonHighlight3"),
    icon12X1237: makeNodeComponent("icon12X1237"),
    text3: makeNodeComponent("text3"),
    icon12X1238: makeNodeComponent("icon12X1238"),
    buttonDefault2: makeNodeComponent("buttonDefault2"),
    icon12X1239: makeNodeComponent("icon12X1239"),
    text4: makeNodeComponent("text4"),
    icon12X1240: makeNodeComponent("icon12X1240"),
    navItemSimple7: makeNodeComponent("navItemSimple7"),
    fahsSection: makeNodeComponent("fahsSection"),
    frame31: makeNodeComponent("frame31"),
    frame32: makeNodeComponent("frame32"),
    frame35: makeNodeComponent("frame35"),
    navItemSimple8: makeNodeComponent("navItemSimple8"),
    // Metadata about props expected for PlasmicSectionMyDashboard
    internalVariantProps: PlasmicSectionMyDashboard__VariantProps,
    internalArgProps: PlasmicSectionMyDashboard__ArgProps
  }
);

export default PlasmicSectionMyDashboard;
/* prettier-ignore-end */
