/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 34tvEQuyqfK98iGCjMbawB
// Component: oIPk7PUdbLu5
import * as React from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicLink as PlasmicLink__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  get as $stateGet,
  hasVariant,
  set as $stateSet,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { usePlasmicDataOp } from "@plasmicapp/react-web/lib/data-sources";
import AsshDropdownLinkItem from "../../AsshDropdownLinkItem"; // plasmic-import: MET00VyMH6Cv/component
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 34tvEQuyqfK98iGCjMbawB/projectcss
import sty from "./PlasmicAsshDropdownButtonExploreAssh.module.css"; // plasmic-import: oIPk7PUdbLu5/css
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: 3hQ14Dlkj5Tr/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: D7O7-9ZHkS8f/icon
import CloseBoldSvgrepoComSvgIcon from "./icons/PlasmicIcon__CloseBoldSvgrepoComSvg"; // plasmic-import: kgKw8A-hT9fj/icon

createPlasmicElementProxy;

export const PlasmicAsshDropdownButtonExploreAssh__VariantProps = new Array(
  "clickedOpen"
);

export const PlasmicAsshDropdownButtonExploreAssh__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAsshDropdownButtonExploreAssh__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  let [$queries, setDollarQueries] = React.useState({});
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "clickedOpen",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.clickedOpen
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $refs
  });
  const new$Queries = {
    getExploreDropdown: usePlasmicDataOp(() => {
      return {
        sourceId: "tbVV8SR67UpQ6Z9zuPcDPB",
        opId: "e4f9998d-b1e6-4a0b-b91b-a7f68c9559f3",
        userArgs: {},
        cacheKey: `plasmic.$.e4f9998d-b1e6-4a0b-b91b-a7f68c9559f3.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);
    $queries = new$Queries;
  }
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root,
        {
          [sty.rootclickedOpen]: hasVariant(
            $state,
            "clickedOpen",
            "clickedOpen"
          )
        }
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox___0WNuI)}>
        <PlasmicLink__
          data-plasmic-name={"exploreAsshDropdownButton"}
          data-plasmic-override={overrides.exploreAsshDropdownButton}
          className={classNames(
            projectcss.all,
            projectcss.a,
            sty.exploreAsshDropdownButton
          )}
          component={Link}
          onClick={async event => {
            const $steps = {};
            $steps["updateClickedOpen"] = true
              ? (() => {
                  const actionArgs = { vgroup: "clickedOpen", operation: 2 };
                  return (({ vgroup, value }) => {
                    if (typeof value === "string") {
                      value = [value];
                    }
                    const oldValue = $stateGet($state, vgroup);
                    $stateSet($state, vgroup, !oldValue);
                    return !oldValue;
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["updateClickedOpen"] != null &&
              typeof $steps["updateClickedOpen"] === "object" &&
              typeof $steps["updateClickedOpen"].then === "function"
            ) {
              $steps["updateClickedOpen"] = await $steps["updateClickedOpen"];
            }
          }}
          platform={"nextjs"}
        >
          <Icon4Icon
            data-plasmic-name={"asshHands"}
            data-plasmic-override={overrides.asshHands}
            className={classNames(projectcss.all, sty.asshHands)}
            role={"img"}
          />

          <div
            data-plasmic-name={"text"}
            data-plasmic-override={overrides.text}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text
            )}
          >
            {"Explore ASSH"}
          </div>
          <Icon5Icon
            data-plasmic-name={"chevronDown"}
            data-plasmic-override={overrides.chevronDown}
            className={classNames(projectcss.all, sty.chevronDown, {
              [sty.chevronDownclickedOpen]: hasVariant(
                $state,
                "clickedOpen",
                "clickedOpen"
              )
            })}
            role={"img"}
          />
        </PlasmicLink__>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__z32Hx)}>
        <section
          data-plasmic-name={"exploreDropdown"}
          data-plasmic-override={overrides.exploreDropdown}
          className={classNames(projectcss.all, sty.exploreDropdown, {
            [sty.exploreDropdownclickedOpen]: hasVariant(
              $state,
              "clickedOpen",
              "clickedOpen"
            )
          })}
        >
          <PlasmicLink__
            data-plasmic-name={"closeLink"}
            data-plasmic-override={overrides.closeLink}
            className={classNames(projectcss.all, projectcss.a, sty.closeLink, {
              [sty.closeLinkclickedOpen]: hasVariant(
                $state,
                "clickedOpen",
                "clickedOpen"
              )
            })}
            component={Link}
            onClick={async event => {
              const $steps = {};
              $steps["updateClickedOpen"] = true
                ? (() => {
                    const actionArgs = {
                      vgroup: "clickedOpen",
                      operation: 6,
                      value: "clickedOpen"
                    };
                    return (({ vgroup, value }) => {
                      if (typeof value === "string") {
                        value = [value];
                      }
                      $stateSet($state, vgroup, false);
                      return false;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateClickedOpen"] != null &&
                typeof $steps["updateClickedOpen"] === "object" &&
                typeof $steps["updateClickedOpen"].then === "function"
              ) {
                $steps["updateClickedOpen"] = await $steps["updateClickedOpen"];
              }
            }}
            platform={"nextjs"}
          >
            <CloseBoldSvgrepoComSvgIcon
              data-plasmic-name={"closeIcon2"}
              data-plasmic-override={overrides.closeIcon2}
              className={classNames(projectcss.all, sty.closeIcon2)}
              role={"img"}
            />
          </PlasmicLink__>
          {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
            (() => {
              try {
                return $queries.getExploreDropdown.data.response.items;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return [];
                }
                throw e;
              }
            })()
          ).map((__plasmic_item_0, __plasmic_idx_0) => {
            const currentItem = __plasmic_item_0;
            const currentIndex = __plasmic_idx_0;
            return (
              <div
                className={classNames(projectcss.all, sty.freeBox__iSRt)}
                key={currentIndex}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___37Gnt)}
                >
                  <AsshDropdownLinkItem
                    data-plasmic-name={"asshDropdownLinkItem"}
                    data-plasmic-override={overrides.asshDropdownLinkItem}
                    assetId={(() => {
                      try {
                        return currentItem.fields.icon.sys.id;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                    className={classNames(
                      "__wab_instance",
                      sty.asshDropdownLinkItem
                    )}
                    label={(() => {
                      try {
                        return currentItem.fields.label;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                    textColor={"var(--token-TYi5l69jClib)"}
                    url={(() => {
                      try {
                        return currentItem.fields.url;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "https://www.assh.org";
                        }
                        throw e;
                      }
                    })()}
                  />
                </div>
              </div>
            );
          })}
        </section>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "exploreAsshDropdownButton",
    "asshHands",
    "text",
    "chevronDown",
    "exploreDropdown",
    "closeLink",
    "closeIcon2",
    "asshDropdownLinkItem"
  ],

  exploreAsshDropdownButton: [
    "exploreAsshDropdownButton",
    "asshHands",
    "text",
    "chevronDown"
  ],

  asshHands: ["asshHands"],
  text: ["text"],
  chevronDown: ["chevronDown"],
  exploreDropdown: [
    "exploreDropdown",
    "closeLink",
    "closeIcon2",
    "asshDropdownLinkItem"
  ],

  closeLink: ["closeLink", "closeIcon2"],
  closeIcon2: ["closeIcon2"],
  asshDropdownLinkItem: ["asshDropdownLinkItem"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAsshDropdownButtonExploreAssh__ArgProps,
          internalVariantPropNames:
            PlasmicAsshDropdownButtonExploreAssh__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAsshDropdownButtonExploreAssh__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAsshDropdownButtonExploreAssh";
  } else {
    func.displayName = `PlasmicAsshDropdownButtonExploreAssh.${nodeName}`;
  }
  return func;
}

export const PlasmicAsshDropdownButtonExploreAssh = Object.assign(
  // Top-level PlasmicAsshDropdownButtonExploreAssh renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    exploreAsshDropdownButton: makeNodeComponent("exploreAsshDropdownButton"),
    asshHands: makeNodeComponent("asshHands"),
    text: makeNodeComponent("text"),
    chevronDown: makeNodeComponent("chevronDown"),
    exploreDropdown: makeNodeComponent("exploreDropdown"),
    closeLink: makeNodeComponent("closeLink"),
    closeIcon2: makeNodeComponent("closeIcon2"),
    asshDropdownLinkItem: makeNodeComponent("asshDropdownLinkItem"),
    // Metadata about props expected for PlasmicAsshDropdownButtonExploreAssh
    internalVariantProps: PlasmicAsshDropdownButtonExploreAssh__VariantProps,
    internalArgProps: PlasmicAsshDropdownButtonExploreAssh__ArgProps
  }
);

export default PlasmicAsshDropdownButtonExploreAssh;
/* prettier-ignore-end */
